/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct __IOHIDDevice* IOHIDDeviceRef;

typedef struct __IOHIDManager* IOHIDManagerRef;

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct SCRCMathAverageValue {
	unsigned samples;
	double fifo[50];
	int fifoIndex;
	double sum;
	double average;
	double current;
} SCRCMathAverageValue;

typedef struct CGPath* CGPathRef;

typedef struct __IOHIDValue* IOHIDValueRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct __IOHIDEventSystemClient* IOHIDEventSystemClientRef;

typedef struct {
	double field1;
	double field2;
	double field3;
	double field4;
} SCD_Struct_HN11;

typedef struct _NSZone* NSZoneRef;

typedef struct __AXObserver* AXObserverRef;

typedef struct CGContext* CGContextRef;

typedef struct opaqueCMSampleBuffer* opaqueCMSampleBufferRef;

typedef struct {
	CGRect field1;
	double field2;
	double field3;
	BOOL field4;
	double field5;
	BOOL field6;
} SCD_Struct_SC16;

typedef struct CGColor* CGColorRef;

typedef struct NSRange {
	unsigned long long location;
	unsigned long long length;
} NSRange;

typedef struct UIEdgeInsets {
	double top;
	double left;
	double bottom;
	double right;
} UIEdgeInsets;

typedef struct CGImage* CGImageRef;

