/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol AXElementFetcherObserver <NSObject>
@optional
-(void)fetcher:(id)arg1 willFetchElementsForEvent:(unsigned long long)arg2 fromApplications:(id)arg3;
-(void)fetcher:(id)arg1 didFetchElementsForEvent:(unsigned long long)arg2 foundNewElements:(BOOL)arg3;
-(void)fetcher:(id)arg1 didScheduleFetchEvent:(unsigned long long)arg2;

@end

