/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, AXAccessQueue, AXSpeechManager;

@interface AXOutputManager : NSObject {

	BOOL _speechEnabled;
	BOOL _soundEffectsEnabled;
	BOOL _audioSessionActive;
	NSMutableDictionary* _registeredSoundIDs;
	AXAccessQueue* _outputAccessQueue;
	AXSpeechManager* _speechManager;

}

@property (nonatomic,readonly) BOOL scanningInterruptsSpeech; 
@property (assign,getter=isAudioSessionActive,nonatomic) BOOL audioSessionActive;                 //@synthesize audioSessionActive=_audioSessionActive - In the implementation block
@property (assign,getter=areSoundEffectsEnabled,nonatomic) BOOL soundEffectsEnabled;              //@synthesize soundEffectsEnabled=_soundEffectsEnabled - In the implementation block
@property (assign,getter=isSpeechEnabled,nonatomic) BOOL speechEnabled;                           //@synthesize speechEnabled=_speechEnabled - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * registeredSoundIDs;                            //@synthesize registeredSoundIDs=_registeredSoundIDs - In the implementation block
@property (nonatomic,retain) AXAccessQueue * outputAccessQueue;                                   //@synthesize outputAccessQueue=_outputAccessQueue - In the implementation block
@property (nonatomic,retain) AXSpeechManager * speechManager;                                     //@synthesize speechManager=_speechManager - In the implementation block
-(BOOL)scanningInterruptsSpeech;
-(void)outputScannerFocusContext:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_setAudioSessionProperties:(id)arg1 ;
-(void)_flushSoundIDs;
-(void)setRegisteredSoundIDs:(NSMutableDictionary *)arg1 ;
-(void)setOutputAccessQueue:(AXAccessQueue *)arg1 ;
-(void)setSpeechManager:(AXSpeechManager *)arg1 ;
-(BOOL)areSoundEffectsEnabled;
-(AXAccessQueue *)outputAccessQueue;
-(NSMutableDictionary *)registeredSoundIDs;
-(void)_playSoundWithSoundID:(unsigned)arg1 ;
-(id)_urlForSoundEffect:(int)arg1 ;
-(id)_voiceOverBundle;
-(BOOL)isSpeechEnabled;
-(void)setSoundEffectsEnabled:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(void)cancelSpeech;
-(void)setSpeechEnabled:(BOOL)arg1 ;
-(void)dispatchSpeechAction:(id)arg1 ;
-(BOOL)isAudioSessionActive;
-(void)setAudioSessionActive:(BOOL)arg1 ;
-(void)playSound:(int)arg1 ;
-(AXSpeechManager *)speechManager;
@end

