/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HNDAccessibilityManagerObserver <NSObject>
@optional
-(void)accessibilityManager:(id)arg1 didReceiveEvent:(long long)arg2;
-(void)accessibilityManager:(id)arg1 didScheduleFetchEvent:(long long)arg2;
-(void)accessibilityManager:(id)arg1 willFetchElementsForEvent:(long long)arg2;
-(void)accessibilityManager:(id)arg1 didFetchElementsForEvent:(long long)arg2 foundNewElements:(BOOL)arg3;
-(void)accessibilityManagerShouldPauseScanning:(id)arg1;
-(void)accessibilityManagerShouldResumeScanning:(id)arg1;

@end

