/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/AXElementFetcherDelegate.h>
#import <assistivetouchd/AXElementFetcherObserver.h>

@protocol OS_dispatch_queue;
@class NSObject, NSMutableDictionary, AXDispatchTimer, AXElementFetcher, NSString, NSMutableArray, NSDate, AXElementGroup, AXElement, NSArray;

@interface HNDAccessibilityManager : NSObject <AXElementFetcherDelegate, AXElementFetcherObserver> {

	NSObject*<OS_dispatch_queue> _appTransitionQueue;
	NSObject*<OS_dispatch_queue> _ignoredTouchRegionsQueue;
	NSMutableDictionary* _pauseCountsByPid;
	BOOL _isPausingScanning;
	AXObserverRef _observer;
	AXDispatchTimer* _elementFetchQueueTimer;
	AXElementFetcher* _elementFetcher;
	NSString* _springboardActionIdentifier;
	NSMutableArray* _accessibilityObservers;
	NSDate* _lastAppTransitionTime;
	AXElementGroup* _rootScannerGroup;
	AXElement* _axOrbPreviewWindow;
	NSArray* _currentApplications;
	NSArray* _ignoredTouchRegions;

}

@property (assign,nonatomic) AXObserverRef observer;                                //@synthesize observer=_observer - In the implementation block
@property (nonatomic,retain) AXElementFetcher * elementFetcher;                     //@synthesize elementFetcher=_elementFetcher - In the implementation block
@property (nonatomic,retain) NSString * springboardActionIdentifier;                //@synthesize springboardActionIdentifier=_springboardActionIdentifier - In the implementation block
@property (nonatomic,retain) NSMutableArray * accessibilityObservers;               //@synthesize accessibilityObservers=_accessibilityObservers - In the implementation block
@property (nonatomic,retain) AXDispatchTimer * elementFetchQueueTimer;              //@synthesize elementFetchQueueTimer=_elementFetchQueueTimer - In the implementation block
@property (nonatomic,readonly) BOOL _isGroupingEnabled; 
@property (nonatomic,readonly) BOOL _isScannerEnabled; 
@property (nonatomic,readonly) BOOL _isSpeechEnabled; 
@property (nonatomic,retain) NSDate * lastAppTransitionTime;                        //@synthesize lastAppTransitionTime=_lastAppTransitionTime - In the implementation block
@property (assign,nonatomic) BOOL isPausingScanning;                                //@synthesize isPausingScanning=_isPausingScanning - In the implementation block
@property (nonatomic,retain) AXElementGroup * rootScannerGroup;                     //@synthesize rootScannerGroup=_rootScannerGroup - In the implementation block
@property (nonatomic,retain) NSArray * currentApplications;                         //@synthesize currentApplications=_currentApplications - In the implementation block
@property (nonatomic,retain) NSArray * ignoredTouchRegions;                         //@synthesize ignoredTouchRegions=_ignoredTouchRegions - In the implementation block
@property (nonatomic,retain) AXElement * axOrbPreviewWindow;                        //@synthesize axOrbPreviewWindow=_axOrbPreviewWindow - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(BOOL)applicationIsRTL;
-(void)refreshElements;
-(id)orbPreviewWindow;
-(void)setAxOrbPreviewWindow:(AXElement *)arg1 ;
-(AXElement *)axOrbPreviewWindow;
-(AXElementFetcher *)elementFetcher;
-(void)setElementFetcher:(AXElementFetcher *)arg1 ;
-(void)_observeNotifications:(BOOL)arg1 ;
-(void)setAccessibilityObservers:(NSMutableArray *)arg1 ;
-(void)setElementFetchQueueTimer:(AXDispatchTimer *)arg1 ;
-(void)setLastAppTransitionTime:(NSDate *)arg1 ;
-(void)setRootScannerGroup:(AXElementGroup *)arg1 ;
-(BOOL)_isGroupingEnabled;
-(BOOL)_isScannerEnabled;
-(BOOL)_isSpeechEnabled;
-(BOOL)_elementFetchingRequired;
-(BOOL)_isElementInIgnoredTouchRegions:(id)arg1 ;
-(void)_initializeAccessibility;
-(NSMutableArray *)accessibilityObservers;
-(void)_enableApplicationAccessibility:(BOOL)arg1 ;
-(NSArray *)ignoredTouchRegions;
-(void)_handleRefreshEvent:(long long)arg1 ;
-(void)setSpringboardActionIdentifier:(NSString *)arg1 ;
-(NSString *)springboardActionIdentifier;
-(void)_notifyObserversDidReceiveEvent:(long long)arg1 ;
-(NSDate *)lastAppTransitionTime;
-(AXElementGroup *)rootScannerGroup;
-(void)setIsPausingScanning:(BOOL)arg1 ;
-(id)_currentAppPids;
-(void)_requestPauseScanning;
-(void)_requestResumeScanning;
-(id)scrollViewsForAction:(int)arg1 elementsToScroll:(id*)arg2 ;
-(id)firstScannerGroupable;
-(id)lastScannerGroupable;
-(id)firstScannerElement;
-(id)lastScannerElement;
-(id)_itemForScanningWithElementCommunity:(id)arg1 useFirst:(BOOL)arg2 ;
-(id)_itemForScanningFromItem:(id)arg1 inDirection:(BOOL)arg2 didWrap:(BOOL*)arg3 ;
-(long long)_hndAccessibilityEventForFetchEvent:(unsigned long long)arg1 ;
-(void)setCurrentApplications:(NSArray *)arg1 ;
-(void)setIgnoredTouchRegions:(NSArray *)arg1 ;
-(BOOL)isPausingScanning;
-(CGRect)screenFrame:(id)arg1 ;
-(void)updateCachedOrbPreviewWindow:(id)arg1 ;
-(void)_handleFirstResponderChanged;
-(void)_handleSystemServerDied;
-(BOOL)frontmostAppMayBeLoading;
-(BOOL)hasZeroElements;
-(void)_handleLayoutChanged;
-(void)_handleAlertAppeared;
-(void)_handleOrientationChanged;
-(void)_handleScreenChanged;
-(void)_handleScreenLocked;
-(void)_handleScrolledByPage;
-(void)_handleKeyboardPopupAppeared;
-(id)_pauseReasonForPid:(int)arg1 ;
-(void)_handlePauseForPid:(int)arg1 ;
-(void)_handleResumeForPid:(int)arg1 ;
-(id)rootKeyboardGroup;
-(id)scrollViewsForAction:(int)arg1 ;
-(id)firstItemForScanningWithElementCommunity:(id)arg1 ;
-(id)lastItemForScanningWithElementCommunity:(id)arg1 ;
-(id)nextItemForScanningFromItem:(id)arg1 didWrap:(BOOL*)arg2 ;
-(id)previousItemForScanningFromItem:(id)arg1 didWrap:(BOOL*)arg2 ;
-(id)firstKeyboardItem;
-(id)scannerElementMatchingElement:(id)arg1 ;
-(void)groupingEnabledDidChange;
-(void)speechEnabledDidChange;
-(void)userDidPerformSwitchAction;
-(AXDispatchTimer *)elementFetchQueueTimer;
-(void)dealloc;
-(id)init;
-(void)addObserver:(id)arg1 ;
-(id)elements;
-(id)firstResponder;
-(void)removeObserver:(id)arg1 ;
-(AXObserverRef)observer;
-(void)setObserver:(AXObserverRef)arg1 ;
-(id)elementAtPoint:(CGPoint)arg1 ;
-(NSArray *)currentApplications;
-(BOOL)isFetchingElements;
-(void)fetcher:(id)arg1 willFetchElementsForEvent:(unsigned long long)arg2 fromApplications:(id)arg3 ;
-(void)fetcher:(id)arg1 didFetchElementsForEvent:(unsigned long long)arg2 foundNewElements:(BOOL)arg3 ;
-(void)fetcher:(id)arg1 didScheduleFetchEvent:(unsigned long long)arg2 ;
-(BOOL)isSystemSleeping:(id)arg1 ;
-(void)_notifyObserversDidScheduleFetchEvent:(long long)arg1 ;
-(void)_notifyObserversWillFetchElementsForEvent:(long long)arg1 ;
-(void)_notifyObserversDidFetchElementsForEvent:(long long)arg1 foundNewElements:(BOOL)arg2 ;
-(BOOL)willFetchElements;
@end

