/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface HNDActionHelper : NSObject
+(id)sharedInstance;
-(void)toggleControlCenter;
-(void)activateSiri;
-(void)activateVoiceControl;
-(void)toggleAppSwitcher;
-(void)activateLockButton;
-(void)decreaseVolume;
-(void)increaseVolume;
-(void)activateTripleClick;
-(void)shake;
-(void)_rotateToOrientation:(int)arg1 ;
-(void)activateHomeButton;
-(void)rotatePortrait;
-(void)rotateUpsideDown;
-(void)rotateLeft;
-(void)rotateRight;
-(void)toggleNotificationCenter;
-(void)takeScreenshot;
-(void)revealSpotlight;
-(void)adjustSystemZoom:(int)arg1 ;
-(void)toggleMute;
@end

