/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIApplication.h>

@class FBSScene;

@interface HNDApplication : UIApplication {

	FBSScene* _mainScene;

}

@property (nonatomic,retain) FBSScene * mainScene;              //@synthesize mainScene=_mainScene - In the implementation block
-(void)setMainScene:(FBSScene *)arg1 ;
-(id)_accessibilityScannerCurrentFocusContext;
-(id)_accessibilityScannerCurrentLoopElementsForFocusContext:(id)arg1 ;
-(id)_accessibilityScannerCurrentLoopElements;
-(unsigned long long)_accessibilityScannerCurrentLoopIndex;
-(BOOL)isSuspended;
-(void)dealloc;
-(id)init;
-(id)_mainSceneForDisplay:(id)arg1 ;
-(void)_runWithMainScene:(id)arg1 transitionContext:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_createStatusBarWithRequestedStyle:(long long)arg1 orientation:(long long)arg2 hidden:(BOOL)arg3 ;
-(FBSScene *)mainScene;
-(id)accessibilityAttributeValue:(int)arg1 ;
@end

