/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <QuartzCore/CAShapeLayer.h>

@class CAShapeLayer;

@interface HNDCursorLayer : CAShapeLayer {

	BOOL _isSelected;
	BOOL _pressed;
	CAShapeLayer* _outerStrokeLayer;
	CAShapeLayer* _innerStrokeLayer;

}

@property (assign,getter=isSelected,nonatomic) BOOL selected;              //@synthesize isSelected=_isSelected - In the implementation block
@property (assign,getter=isPressed,nonatomic) BOOL pressed;                //@synthesize pressed=_pressed - In the implementation block
@property (nonatomic,retain) CAShapeLayer * outerStrokeLayer;              //@synthesize outerStrokeLayer=_outerStrokeLayer - In the implementation block
@property (nonatomic,retain) CAShapeLayer * innerStrokeLayer;              //@synthesize innerStrokeLayer=_innerStrokeLayer - In the implementation block
-(void)setOuterStrokeLayer:(CAShapeLayer *)arg1 ;
-(void)setInnerStrokeLayer:(CAShapeLayer *)arg1 ;
-(CAShapeLayer *)outerStrokeLayer;
-(CAShapeLayer *)innerStrokeLayer;
-(void)animateToTapWithDuration:(double)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setPressed:(BOOL)arg1 ;
-(BOOL)isSelected;
-(void)setSelected:(BOOL)arg1 ;
-(BOOL)isPressed;
@end

