/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSArray;

@interface HNDCustomGesture : NSObject <NSCopying> {

	BOOL _isDoubleTap;
	BOOL _shouldPerformAtOriginalLocation;
	BOOL _hasLocalizableName;
	NSString* _name;
	NSArray* _points;
	NSArray* _times;
	NSArray* _forces;
	long long _orbGestureType;

}

@property (nonatomic,retain) NSString * name;                                   //@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSArray * points;                                  //@synthesize points=_points - In the implementation block
@property (nonatomic,retain) NSArray * times;                                   //@synthesize times=_times - In the implementation block
@property (nonatomic,retain) NSArray * forces;                                  //@synthesize forces=_forces - In the implementation block
@property (assign,nonatomic) long long orbGestureType;                          //@synthesize orbGestureType=_orbGestureType - In the implementation block
@property (assign,nonatomic) BOOL isDoubleTap;                                  //@synthesize isDoubleTap=_isDoubleTap - In the implementation block
@property (assign,nonatomic) BOOL shouldPerformAtOriginalLocation;              //@synthesize shouldPerformAtOriginalLocation=_shouldPerformAtOriginalLocation - In the implementation block
@property (assign,nonatomic) BOOL hasLocalizableName;                           //@synthesize hasLocalizableName=_hasLocalizableName - In the implementation block
+(id)gestureWithDictionary:(id)arg1 ;
-(void)perform;
-(void)setOrbGestureType:(long long)arg1 ;
-(void)setShouldPerformAtOriginalLocation:(BOOL)arg1 ;
-(void)setHasLocalizableName:(BOOL)arg1 ;
-(void)setForces:(NSArray *)arg1 ;
-(void)setIsDoubleTap:(BOOL)arg1 ;
-(long long)orbGestureType;
-(NSArray *)forces;
-(BOOL)isDoubleTap;
-(BOOL)shouldPerformAtOriginalLocation;
-(BOOL)hasLocalizableName;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(id)_initWithDictionary:(id)arg1 ;
-(NSArray *)points;
-(void)setPoints:(NSArray *)arg1 ;
-(NSArray *)times;
-(void)setTimes:(NSArray *)arg1 ;
@end

