/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HNDDeviceDetectorDelegate;
#import <assistivetouchd/assistivetouchd-Structs.h>
@interface HNDDeviceDetector : NSObject {

	IOHIDManagerRef _hidManager;
	id<HNDDeviceDetectorDelegate> _delegate;
	BOOL _detectDevices;

}

@property (assign,nonatomic) BOOL detectDevices;                                  //@synthesize detectDevices=_detectDevices - In the implementation block
@property (assign,nonatomic) id<HNDDeviceDetectorDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(void)initialize;
+(id)sharedDetector;
-(void)setDetectDevices:(BOOL)arg1 ;
-(BOOL)detectDevices;
-(id)_matchingDictionaries;
-(void)setDelegate:(id<HNDDeviceDetectorDelegate>)arg1 ;
-(id)init;
-(id<HNDDeviceDetectorDelegate>)delegate;
@end

