/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATElementManager.h>

@protocol HNDElementNavigationControllerDelegate;
@class SCATFocusContext, NSValue, NSIndexPath, AXElement, UIView, HNDAccessibilityManager;

@interface HNDElementNavigationController : SCATElementManager {

	BOOL _shouldRescanAfterFetch;
	BOOL _shouldRescanFromTopAfterFetch;
	BOOL _shouldScanKeyboardOnAppearance;
	BOOL _menuOpeningElementEnabled;
	int _keyboardSelectBehavior;
	id<HNDElementNavigationControllerDelegate> _delegate;
	SCATFocusContext* _currentFocusContext;
	NSValue* _keyboardKeyCenterPoint;
	NSIndexPath* _keyboardIndexPath;
	AXElement* _lastScannedElementCommunity;
	AXElement* _firstResponder;
	UIView* _menuOpeningElement;

}

@property (assign,nonatomic) id<HNDElementNavigationControllerDelegate> delegate;                            //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) SCATFocusContext * currentFocusContext;                                         //@synthesize currentFocusContext=_currentFocusContext - In the implementation block
@property (nonatomic,readonly) BOOL isGroupingEnabled; 
@property (nonatomic,readonly) HNDAccessibilityManager * axManager; 
@property (assign,nonatomic) BOOL shouldRescanAfterFetch;                                                    //@synthesize shouldRescanAfterFetch=_shouldRescanAfterFetch - In the implementation block
@property (assign,nonatomic) BOOL shouldRescanFromTopAfterFetch;                                             //@synthesize shouldRescanFromTopAfterFetch=_shouldRescanFromTopAfterFetch - In the implementation block
@property (nonatomic,retain) NSValue * keyboardKeyCenterPoint;                                               //@synthesize keyboardKeyCenterPoint=_keyboardKeyCenterPoint - In the implementation block
@property (nonatomic,retain) NSIndexPath * keyboardIndexPath;                                                //@synthesize keyboardIndexPath=_keyboardIndexPath - In the implementation block
@property (assign,nonatomic) int keyboardSelectBehavior;                                                     //@synthesize keyboardSelectBehavior=_keyboardSelectBehavior - In the implementation block
@property (nonatomic,retain) AXElement * lastScannedElementCommunity;                                        //@synthesize lastScannedElementCommunity=_lastScannedElementCommunity - In the implementation block
@property (nonatomic,retain) AXElement * firstResponder;                                                     //@synthesize firstResponder=_firstResponder - In the implementation block
@property (assign,nonatomic) BOOL shouldScanKeyboardOnAppearance;                                            //@synthesize shouldScanKeyboardOnAppearance=_shouldScanKeyboardOnAppearance - In the implementation block
@property (assign,getter=isMenuOpeningElementEnabled,nonatomic) BOOL menuOpeningElementEnabled;              //@synthesize menuOpeningElementEnabled=_menuOpeningElementEnabled - In the implementation block
@property (nonatomic,retain) UIView * menuOpeningElement;                                                    //@synthesize menuOpeningElement=_menuOpeningElement - In the implementation block
-(void)driver:(id)arg1 willUnfocusFromContext:(id)arg2 ;
-(void)driver:(id)arg1 didFocusOnContext:(id)arg2 ;
-(id)lastElementWithOptions:(int*)arg1 ;
-(id)firstElementWithOptions:(int*)arg1 ;
-(id)focusContextAfterDrillOutOnGroup:(id)arg1 ;
-(id)numberOfItemsInCurrentScanCycle;
-(void)didFetchElements:(id)arg1 foundNewElements:(BOOL)arg2 currentFocusContext:(id)arg3 didChangeActiveElementManager:(BOOL)arg4 ;
-(id)elementAfter:(id)arg1 didWrap:(BOOL*)arg2 options:(int*)arg3 ;
-(id)elementBefore:(id)arg1 didWrap:(BOOL*)arg2 options:(int*)arg3 ;
-(void)scannerWillMakeManagerInactive:(id)arg1 ;
-(UIView *)menuOpeningElement;
-(void)_menuOpeningElementActivated:(id)arg1 ;
-(void)setMenuOpeningElement:(UIView *)arg1 ;
-(HNDAccessibilityManager *)axManager;
-(AXElement *)lastScannedElementCommunity;
-(BOOL)isMenuOpeningElementEnabled;
-(SCATFocusContext *)currentFocusContext;
-(BOOL)shouldRescanFromTopAfterFetch;
-(BOOL)shouldRescanAfterFetch;
-(void)_resetFetchFlags;
-(void)_giveUpWaitingForFetchAfterPause;
-(void)_stopWaitingForFetchAfterTemporaryPause;
-(void)setShouldRescanAfterFetch:(BOOL)arg1 ;
-(void)_pauseScanningTemporarily;
-(void)setShouldRescanFromTopAfterFetch:(BOOL)arg1 ;
-(void)_startWaitingForFetchAfterTemporaryPause;
-(BOOL)_didFocusLastOnKeyboardElement;
-(void)firstResponderDidChange:(id)arg1 ;
-(void)_pauseScanningForLikelyScreenChange;
-(void)setLastScannedElementCommunity:(AXElement *)arg1 ;
-(void)setShouldScanKeyboardOnAppearance:(BOOL)arg1 ;
-(id)_firstKeyboardFocusContext;
-(void)setFirstResponder:(AXElement *)arg1 ;
-(void)setMenuOpeningElementEnabled:(BOOL)arg1 ;
-(void)setCurrentFocusContext:(SCATFocusContext *)arg1 ;
-(void)_trackLastFocusedKeyboardItem:(id)arg1 ;
-(void)_trackLastScannedElementCommunityFromFocusContext:(id)arg1 ;
-(void)_updateMenuOpeningElementEnabledWithFocusContext:(id)arg1 ;
-(void)setKeyboardIndexPath:(NSIndexPath *)arg1 ;
-(void)setKeyboardKeyCenterPoint:(NSValue *)arg1 ;
-(unsigned long long)_depthForElement:(id)arg1 ;
-(id)_replacementForLastFocusedKeyboardItem;
-(BOOL)shouldScanKeyboardOnAppearance;
-(void)_attemptToRestoreFocusContext:(id)arg1 scannerManager:(id)arg2 ;
-(BOOL)_isKeyboardContainerElement:(id)arg1 allowKeyboardContainerItself:(BOOL)arg2 ;
-(NSIndexPath *)keyboardIndexPath;
-(NSValue *)keyboardKeyCenterPoint;
-(id)_indexPathForKeyboardElement:(id)arg1 ;
-(id)_keyboardElementForIndexPath:(id)arg1 ;
-(BOOL)_isScanningKeyboardContainer:(id)arg1 ;
-(void)setKeyboardSelectBehavior:(int)arg1 ;
-(int)keyboardSelectBehavior;
-(void)appTransitionDidOccur:(id)arg1 ;
-(void)screenDidChange:(id)arg1 ;
-(void)alertDidAppear:(id)arg1 ;
-(void)screenChangingButtonWasPressed:(id)arg1 ;
-(void)scannerManager:(id)arg1 didActivateElement:(id)arg2 ;
-(id)nextFocusContextAfterDismissingMenuForElement:(id)arg1 ;
-(void)setDelegate:(id<HNDElementNavigationControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<HNDElementNavigationControllerDelegate>)delegate;
-(id)identifier;
-(AXElement *)firstResponder;
-(BOOL)isGroupingEnabled;
-(void)orientationDidChange:(id)arg1 ;
@end

