/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <assistivetouchd/assistivetouchd-Structs.h>
@class SCRCThread, NSMutableArray, NSLock, NSString, NSThread, AXAssertion;

@interface HNDEventManager : NSObject {

	SCRCThread* _eventDispatchThread;
	NSMutableArray* _eventsToDispatch;
	NSMutableArray* _eventsToMatch;
	CFRunLoopSourceRef _source;
	CFRunLoopRef _runLoop;
	NSLock* _eventLock;
	BOOL _isCapturingEvents;
	BOOL _nubbitMoving;
	NSString* _axSpringBoardCallbackIdentifier;
	NSThread* _ioFilterThread;
	IOHIDEventSystemClientRef _ioSystemFilterClient;
	IOHIDEventSystemClientRef _ioSystemPostBackClient;
	AXAssertion* _disableSystemGesturesAssertion;
	IOHIDEventSystemClientRef _ioSystemClient;

}

@property (nonatomic,retain) AXAssertion * disableSystemGesturesAssertion;              //@synthesize disableSystemGesturesAssertion=_disableSystemGesturesAssertion - In the implementation block
@property (nonatomic,readonly) BOOL isCapturingEvents;                                  //@synthesize isCapturingEvents=_isCapturingEvents - In the implementation block
@property (nonatomic,readonly) IOHIDEventSystemClientRef ioSystemClient;                //@synthesize ioSystemClient=_ioSystemClient - In the implementation block
+(void)initialize;
+(id)sharedManager;
-(void)resetEventManager;
-(void)setCaptureEvents:(BOOL)arg1 ;
-(void)setNubbitMoving:(BOOL)arg1 ;
-(void)performCancel;
-(void)systemServerRestarted;
-(void)performDownWithFingers:(id)arg1 ;
-(void)performUpWithFingers:(id)arg1 ;
-(void)performMoveWithFingers:(id)arg1 ;
-(void)notifyUserEventOccurred;
-(void)performHardwareButton:(int)arg1 state:(int)arg2 ;
-(void)performDownWithPointsByFingerIdentifier:(id)arg1 ;
-(void)performMoveWithPointsByFingerIdentifier:(id)arg1 ;
-(void)performUpWithPointsByFingerIdentifier:(id)arg1 ;
-(BOOL)isCapturingEvents;
-(void)wakeDeviceFromSleepIfNecessary;
-(void)manipulateDimTimer:(BOOL)arg1 ;
-(void)ringerSwitchChanged;
-(void)rotationLockChanged;
-(void)substantialTransitionOccurred;
-(void)_startThread;
-(void)_initializeASTNotificationCenter;
-(void)_initializeSystemWideServerPort;
-(void)_initializeSpringBoardItems;
-(void)_resetEventManager;
-(void)_unregisterIOFilter;
-(void)keyboardStatusChanged:(id)arg1 userInfo:(id)arg2 ;
-(void)mediaControlsChanged:(id)arg1 userInfo:(id)arg2 ;
-(void)_disableIOFilter;
-(void)_startIOThread;
-(void)_registerIOHIDUsage;
-(void)_sendEventRepresentation:(id)arg1 ;
-(id)_assignFingerIdentifiersToPoints:(id)arg1 ;
-(void)_sendHandEvent:(unsigned)arg1 pointsByFingerIdentifier:(id)arg2 ;
-(void)_sendButtonEvent:(unsigned)arg1 ;
-(void)_sendShakeEvent;
-(void)_sendDeviceOrientationChange:(int)arg1 ;
-(void)_takeScreenshot;
-(void)_toggleAppSwitcher;
-(void)_toggleSiri;
-(void)_toggleVoiceControl;
-(void)_tripleClick;
-(void)_restartConnectionToSystemServer;
-(void)_handleIOHIDEvent:(id)arg1 ;
-(BOOL)sideSwitchUsedForOrientation;
-(BOOL)orientationLocked;
-(void)openCreateCustomGestureForAST;
-(void)openCreateCustomGestureForSCAT;
-(void)_performPressAndHoldMenu:(float)arg1 ;
-(IOHIDEventSystemClientRef)ioSystemClient;
-(id)init;
-(int)deviceOrientation;
-(void)setMenuVisible:(BOOL)arg1 ;
-(void)setOrientationLocked:(BOOL)arg1 ;
-(double)volumeLevel;
-(BOOL)isVoiceControlRunning;
-(AXAssertion *)disableSystemGesturesAssertion;
-(void)setDisableSystemGesturesAssertion:(AXAssertion *)arg1 ;
-(void)_processQueue;
@end

