/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/HNDView.h>

@class HNDCursorLayer;

@interface HNDFingerView : HNDView {

	BOOL _actualVisibility;
	HNDCursorLayer* _cursorLayer;

}

@property (assign,nonatomic) BOOL selected; 
@property (nonatomic,readonly) double radius; 
@property (nonatomic,retain) HNDCursorLayer * cursorLayer;              //@synthesize cursorLayer=_cursorLayer - In the implementation block
+(CGSize)fingerSize;
+(double)fingerInnerRadius;
+(id)strokeOutlineColor;
+(id)deselectedFillColor;
+(double)strokeOutlineWidth;
+(id)deselectedStrokeColor;
+(double)fingerInnerCircleInnerRadius;
+(id)selectedStrokeColor;
+(double)fingerRadius;
+(id)selectedFillColor;
+(double)fingerOuterRadius;
+(double)strokeWidth;
-(void)implode:(BOOL)arg1 ;
-(void)explode:(BOOL)arg1 ;
-(void)cancelImplodeAnimation;
-(void)implodeDisplayLinkFired:(id)arg1 ;
-(void)setIsPinchFinger:(long long)arg1 ;
-(void)animateToTapWithDuration:(double)arg1 ;
-(HNDCursorLayer *)cursorLayer;
-(void)setCursorLayer:(HNDCursorLayer *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setFrame:(CGRect)arg1 ;
-(BOOL)isUserInteractionEnabled;
-(void)setSelected:(BOOL)arg1 ;
-(BOOL)isVisible;
-(BOOL)selected;
-(void)setVisible:(BOOL)arg1 animated:(BOOL)arg2 ;
@end

