/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface HNDHoverCursorCircle : UIView {

	BOOL _fill;
	BOOL _dashed;
	BOOL _selected;
	UIView* _innerCircle;
	double _radiusMultiplier;

}

@property (assign,nonatomic) BOOL fill;                            //@synthesize fill=_fill - In the implementation block
@property (assign,nonatomic) BOOL dashed;                          //@synthesize dashed=_dashed - In the implementation block
@property (assign,nonatomic) BOOL selected;                        //@synthesize selected=_selected - In the implementation block
@property (assign,nonatomic) double radiusMultiplier;              //@synthesize radiusMultiplier=_radiusMultiplier - In the implementation block
@property (nonatomic,readonly) double radius; 
-(void)showInnerCircle:(BOOL)arg1 ;
-(void)setRadiusMultiplier:(double)arg1 ;
-(double)radiusMultiplier;
-(BOOL)dashed;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(BOOL)fill;
-(void)setSelected:(BOOL)arg1 ;
-(BOOL)selected;
-(double)radius;
-(void)setDashed:(BOOL)arg1 ;
-(void)setFill:(BOOL)arg1 ;
@end

