/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UIView.h>

@interface HNDMultiFinger : UIView {

	BOOL _recorded;
	BOOL _finalized;
	BOOL _imploded;

}
-(void)_drawCircle:(CGPoint)arg1 radius:(double)arg2 color:(id)arg3 ;
-(void)setFinalized:(BOOL)arg1 ;
-(void)implode;
-(void)setRecorded:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)explode;
@end

