/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <ScreenReaderCore/SCRCArgumentParser.h>

@interface HNDMain : SCRCArgumentParser {

	CFRunLoopRef _mainRunLoop;
	BOOL _stop;
	BOOL _springboardReady;
	BOOL _keepAlive;

}

@property (assign,nonatomic) BOOL springboardReady;              //@synthesize springboardReady=_springboardReady - In the implementation block
+(id)processIdentifier;
+(id)commandPath;
+(id)versionString;
-(void)_springBoardDied:(id)arg1 ;
-(void)setKeepAlive:(BOOL)arg1 ;
-(void)_goDogGo:(id)arg1 ;
-(void)_assistiveTouchSettingsChanged;
-(void)_initializeSystemSettings;
-(void)_assistiveTouchEnabledChange;
-(void)_scannerEnabledChange;
-(BOOL)springboardReady;
-(void)setSpringboardReady:(BOOL)arg1 ;
-(void)stop;
-(int)run;
-(id)initWithArgc:(int)arg1 argv:(const char**)arg2 ;
@end

