/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/HNDView.h>

@interface HNDPinchChainView : HNDView {

	CGPoint _startPoint;
	CGPoint _endPoint;
	BOOL _pressed;
	int pinchChainMode;

}

@property (assign,nonatomic) CGPoint startPoint;                         //@synthesize startPoint=_startPoint - In the implementation block
@property (assign,nonatomic) CGPoint endPoint;                           //@synthesize endPoint=_endPoint - In the implementation block
@property (assign,getter=isPressed,nonatomic) BOOL pressed;              //@synthesize pressed=_pressed - In the implementation block
@property (assign,nonatomic) int pinchChainMode; 
-(void)setPinchChainMode:(int)arg1 ;
-(int)pinchChainMode;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(BOOL)isUserInteractionEnabled;
-(void)setStartPoint:(CGPoint)arg1 ;
-(void)setEndPoint:(CGPoint)arg1 ;
-(void)setPressed:(BOOL)arg1 ;
-(CGPoint)startPoint;
-(BOOL)isPressed;
-(CGPoint)endPoint;
-(CGPoint)midPoint;
@end

