/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/HNDView.h>
#import <assistivetouchd/HNDRockerButtonDataSource.h>

@class NSMutableArray, HNDRockerButton, HNDFingerView, CADisplayLink, AXDispatchTimer, UIImageView, HNDVolumeBar, _UIBackdropView, NSString;

@interface HNDRocker : HNDView <HNDRockerButtonDataSource> {

	int _state;
	NSMutableArray* _stackState;
	NSMutableArray* _rockerItems;
	HNDRockerButton* _selectedButton;
	HNDRockerButton* _backButton;
	long long _selectedButtonIndex;
	int _backgroundType;
	HNDFingerView* _middleCircle;
	CGPoint _initialPoint;
	BOOL _isFullMenuVisible;
	BOOL _isNubbitVisible;
	BOOL _useCircle;
	double _progress;
	BOOL _sentRockers;
	BOOL _linkRunning;
	CADisplayLink* _rockerLink;
	double _startInterval;
	AXDispatchTimer* _homeButtonDismissTimer;
	int _style;
	BOOL _nubbitDimmed;
	AXDispatchTimer* _nubbitFadeTimer;
	UIImageView* _nubbitForeground;
	BOOL _animatingNubbit;
	AXDispatchTimer* _volumeHideTimer;
	AXDispatchTimer* _volumeUpdateTimer;
	HNDVolumeBar* _volumeBar;
	_UIBackdropView* _backdropView;

}

@property (assign,nonatomic) int style;                             //@synthesize style=_style - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(CGSize)nubbitSize;
+(CGSize)initialRockerSize;
-(void)highlightNubbit;
-(void)fadeNubbit;
-(BOOL)isAnimatingNubbit;
-(BOOL)customizationMapAllowInstanceActivation:(id)arg1 ;
-(void)handleRealUpEvent:(CGPoint)arg1 maxOrc:(double)arg2 ;
-(void)modalizeMenu:(BOOL)arg1 modalButton:(id)arg2 ;
-(void)handleRealDownEvent:(CGPoint)arg1 ;
-(BOOL)isFullMenuVisible;
-(void)updateRockersForSubstantialTransition;
-(CGPoint)onScreenLocation;
-(void)transitionMenuToNubbit:(CGPoint)arg1 changeAlpha:(BOOL)arg2 animate:(BOOL)arg3 ;
-(BOOL)hoveredTo:(CGPoint)arg1 ;
-(void)implodeDisplayLinkFired:(id)arg1 ;
-(void)performPress:(int)arg1 type:(int)arg2 ;
-(void)setUseCircleMode:(BOOL)arg1 ;
-(void)showMiddleCircle:(BOOL)arg1 ;
-(void)transitionNubbitToMenu:(CGPoint)arg1 animationCompleted:(/*^block*/id)arg2 ;
-(void)setFullMenuVisible:(BOOL)arg1 atPoint:(CGPoint)arg2 ;
-(void)setNubbitVisible:(BOOL)arg1 ;
-(void)updateRingerSwitch;
-(void)updateRotationLockSwitch;
-(void)volumeChanged;
-(void)activateMenuItemDown:(id)arg1 ;
-(void)activateMenuItemUp:(id)arg1 ;
-(void)_goBackInMenuState:(int)arg1 ;
-(void)_siriPrefsChanged:(id)arg1 ;
-(void)_loadMenuItems:(BOOL)arg1 iconStartPoint:(CGPoint)arg2 goBackwards:(BOOL)arg3 originalState:(int)arg4 ;
-(long long)_indexForAngle:(double)arg1 ;
-(id)_rockerHitTest:(CGPoint)arg1 ;
-(void)_updateSelectedButton;
-(void)showVolumeBar:(BOOL)arg1 withProgress:(double)arg2 ;
-(void)_notificationCenterPressed;
-(void)_pinchPressed:(id)arg1 ;
-(void)_doubleTapPressed:(id)arg1 ;
-(void)_orbPressed:(id)arg1 ;
-(void)_lockButton:(BOOL)arg1 ;
-(void)_volumeDown:(BOOL)arg1 ;
-(void)_volumeUp:(BOOL)arg1 ;
-(void)_tripleClickHomePressed;
-(void)_orientationPressed:(id)arg1 ;
-(void)_ringerPressed;
-(void)_setRingerSwitchIcon:(id)arg1 ;
-(void)_rotationLockPressed;
-(void)_setRotationLockIcon:(id)arg1 ;
-(void)_screenshotPressed;
-(void)_shakePressed;
-(void)_multiTasking;
-(void)_hardwareButtonPressed:(id)arg1 ;
-(void)_controlCenterPressed;
-(void)_homeButton:(BOOL)arg1 ;
-(void)_customsPressed:(id)arg1 ;
-(id)_rockerButtonForLocation:(id)arg1 buttonType:(id)arg2 ;
-(void)_siriButtonPressed;
-(void)_voiceControlPressed;
-(void)_gesturesPressed:(id)arg1 ;
-(void)_customGesturePressed:(id)arg1 ;
-(void)_handleTouch:(long long)arg1 ;
-(void)_handleRotate:(int)arg1 ;
-(BOOL)_replaceRingerWithOrientationLock;
-(BOOL)_includeRingerButtonInHardware;
-(void)_morePressed:(id)arg1 ;
-(void)_addFavoriteBoxPressed;
-(id)rockerButtons;
-(void)_layoutButton:(id)arg1 withPoint:(CGPoint)arg2 ;
-(void)_resetRockerButtons:(CGPoint)arg1 ;
-(void)_layoutBackButton;
-(CGPathRef)_pieSlice:(long long)arg1 withSlices:(long long)arg2 ;
-(void)_layoutButtonsWithAlpha:(double)arg1 startPoint:(CGPoint)arg2 ;
-(void)_addNewButtonsToView;
-(void)_mutePressed;
-(void)_setBackgroundWithType:(int)arg1 ;
-(void)_layoutEightRockers:(CGPoint)arg1 ;
-(void)_layoutInitialStateItems:(CGPoint)arg1 ;
-(void)_layoutTwoRockers:(CGPoint)arg1 ;
-(void)_layoutFourRockers:(CGPoint)arg1 ;
-(void)_layoutFiveOrSixRockers:(CGPoint)arg1 ;
-(void)_layoutArbitraryRockers:(CGPoint)arg1 ;
-(void)_loadInitialMenuItems;
-(void)_loadHardwareMenuItems;
-(void)_loadFavoritesMenuItems;
-(void)_loadRotateMenuItems;
-(void)_loadGesturesMenuItems;
-(void)_loadMoreMenuItems;
-(id)animationEndButtonForButtonTag:(int)arg1 ;
-(void)_layoutMenuItemsInReverse:(BOOL)arg1 oldRockers:(id)arg2 animateToIcon:(id)arg3 ;
-(void)_layoutMenuItems:(BOOL)arg1 oldRockers:(id)arg2 iconStartPoint:(CGPoint)arg3 ;
-(void)_resetHoverCircleLocation;
-(void)_updateVolumeDisplay;
-(void)showVolumeDisplayImmediately;
-(void)_resetVisibility:(BOOL)arg1 ;
-(void)_initializeNubbit;
-(SCD_Struct_HN11)rockerButtonGuttersForRockerButton:(id)arg1 ;
-(void)_highlightRockerButtonAtAngle:(double)arg1 ;
-(BOOL)_angleIndicatesReturnToCenter:(double)arg1 ;
-(void)_swipePressed;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setFrame:(CGRect)arg1 ;
-(int)state;
-(int)style;
-(void)setStyle:(int)arg1 ;
-(id)accessibilityLabel;
-(id)accessibilityHint;
-(BOOL)isAccessibilityElement;
-(BOOL)accessibilityPerformEscape;
-(void)cleanup;
-(void)_updateProgress:(id)arg1 ;
@end

