/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/HNDAnimationFactory.h>

@interface HNDSpringAnimationFactory : HNDAnimationFactory {

	double _mass;
	double _stiffness;
	double _damping;

}

@property (nonatomic,readonly) double mass;                   //@synthesize mass=_mass - In the implementation block
@property (nonatomic,readonly) double stiffness;              //@synthesize stiffness=_stiffness - In the implementation block
@property (nonatomic,readonly) double damping;                //@synthesize damping=_damping - In the implementation block
+(id)factoryWithMass:(double)arg1 stiffness:(double)arg2 damping:(double)arg3 ;
-(id)_initWithMass:(double)arg1 stiffness:(double)arg2 damping:(double)arg3 ;
-(void)_calculateDuration;
-(id)_springAnimation;
-(double)damping;
-(double)mass;
-(id)_animation;
-(double)stiffness;
@end

