/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/_UIRootWindow.h>

@protocol HNDWindowDelegateProtocol;
@interface HNDWindow : _UIRootWindow {

	id<HNDWindowDelegateProtocol> _hitTestDelegate;

}

@property (assign,nonatomic) id<HNDWindowDelegateProtocol> hitTestDelegate;              //@synthesize hitTestDelegate=_hitTestDelegate - In the implementation block
+(BOOL)_isSecure;
-(BOOL)acceptsGlobalPoint:(CGPoint)arg1 ;
-(id<HNDWindowDelegateProtocol>)hitTestDelegate;
-(void)setHitTestDelegate:(id<HNDWindowDelegateProtocol>)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(BOOL)_alwaysGetsContexts;
@end

