/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATSimpleElement.h>

@protocol SCATGestureFingersElementDelegate;
@interface SCATGestureFingersElement : SCATSimpleElement {

	id<SCATGestureFingersElementDelegate> _delegate;

}

@property (assign,nonatomic) id<SCATGestureFingersElementDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(BOOL)scatIndicatesOwnFocus;
-(void)scatDidBecomeFocused:(BOOL)arg1 ;
-(id)scatSpeakableDescription;
-(BOOL)scatPerformAction:(int)arg1 ;
-(void)setDelegate:(id<SCATGestureFingersElementDelegate>)arg1 ;
-(id<SCATGestureFingersElementDelegate>)delegate;
@end

