/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATModernMenuItemDelegate.h>

@class NSArray, SCATStaticElementProvider, UIViewController, UICollectionViewLayout, SCATMenu, UICollectionView, SCATModernMenuViewController, SCATModernMenuSheetCollectionViewController, NSString;

@interface SCATModernMenuSheet : NSObject <SCATModernMenuItemDelegate> {

	NSArray* _menuItems;
	BOOL _collectionBased;
	BOOL _shouldIncludeBackItem;
	SCATStaticElementProvider* _elementProvider;
	UIViewController* _viewController;
	UICollectionViewLayout* _collectionViewLayout;
	SCATMenu* _menu;
	UICollectionView* _collectionView;

}

@property (assign,getter=isCollectionBased,nonatomic) BOOL collectionBased;                                             //@synthesize collectionBased=_collectionBased - In the implementation block
@property (nonatomic,retain) UIViewController * viewController;                                                         //@synthesize viewController=_viewController - In the implementation block
@property (assign,nonatomic) SCATMenu * menu;                                                                           //@synthesize menu=_menu - In the implementation block
@property (nonatomic,readonly) SCATModernMenuViewController * menuViewController; 
@property (nonatomic,retain,readonly) SCATStaticElementProvider * elementProvider;                                      //@synthesize elementProvider=_elementProvider - In the implementation block
@property (assign,nonatomic) BOOL shouldIncludeBackItem;                                                                //@synthesize shouldIncludeBackItem=_shouldIncludeBackItem - In the implementation block
@property (nonatomic,retain) UICollectionViewLayout * collectionViewLayout;                                             //@synthesize collectionViewLayout=_collectionViewLayout - In the implementation block
@property (nonatomic,retain) UICollectionView * collectionView;                                                         //@synthesize collectionView=_collectionView - In the implementation block
@property (nonatomic,retain) NSArray * menuItems; 
@property (nonatomic,readonly) SCATModernMenuSheetCollectionViewController * scatCollectionViewController; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)isValidForElement:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(id)menuItemStruts;
-(BOOL)allowsBackAction;
-(BOOL)allowsExitAction;
-(BOOL)shouldAllowDwellSelection;
-(BOOL)shouldKeepScannerAwake;
-(id)backTitle;
-(BOOL)shouldUseBackItemAsDoneItem;
-(long long)preferredTipObject;
-(void)didChangeOrientation;
-(CGRect)rectToClear;
-(id)alternateTipElement;
-(BOOL)delegatesScannerControl;
-(void)willFocusOnContext:(id)arg1 ;
-(void)didFocusOnContext:(id)arg1 ;
-(void)willUnfocusFromContext:(id)arg1 ;
-(void)viewControllerViewWillDisappear:(BOOL)arg1 ;
-(BOOL)shouldIncludeTextLabels;
-(void)viewControllerViewWillAppear:(BOOL)arg1 ;
-(unsigned long long)presentationMode;
-(BOOL)shouldUpdateMenuItem:(id)arg1 ;
-(void)menuItemWasActivated:(id)arg1 ;
-(SCATStaticElementProvider *)elementProvider;
-(id)initWithMenu:(id)arg1 ;
-(void)_setupForCollectionBasedSheet;
-(void)didPressScreenChangingButton;
-(SCATModernMenuViewController *)menuViewController;
-(void)setShouldIncludeBackItem:(BOOL)arg1 ;
-(BOOL)isCollectionBased;
-(unsigned long long)numberOfPagesRequired;
-(id)menuItemsForCustomActions:(id)arg1 activateBehavior:(unsigned long long)arg2 ;
-(unsigned long long)numberOfItemsInFirstPage;
-(void)invalidateMenuItems;
-(BOOL)isBackItemIdentifier:(id)arg1 ;
-(Class)_menuItemClass;
-(void)setCollectionBased:(BOOL)arg1 ;
-(BOOL)shouldIncludeBackItem;
-(id)_filteredMenuItemsForGuidedAccessIfNeeded:(id)arg1 ;
-(id)_scannerGroupsForMenuItems:(id)arg1 ;
-(SCATModernMenuSheetCollectionViewController *)scatCollectionViewController;
-(id)_fallbackImageForCustomActionMenuItem:(id)arg1 charactersInUse:(id)arg2 ;
-(void)_setupForCustomSheet:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(NSString *)description;
-(void)reload;
-(UICollectionViewLayout *)collectionViewLayout;
-(UICollectionView *)collectionView;
-(void)setViewController:(UIViewController *)arg1 ;
-(UIViewController *)viewController;
-(unsigned long long)currentPage;
-(void)setCollectionView:(UICollectionView *)arg1 ;
-(void)setMenuItems:(NSArray *)arg1 ;
-(void)setCollectionViewLayout:(UICollectionViewLayout *)arg1 ;
-(NSArray *)menuItems;
-(SCATMenu *)menu;
-(void)setMenu:(SCATMenu *)arg1 ;
-(id)itemWithIdentifier:(id)arg1 ;
@end

