/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UIControl.h>

@class UIImage;

@interface SCATMenuOpeningElement : UIControl {

	UIImage* _backdropMaskImage;

}

@property (nonatomic,retain) UIImage * backdropMaskImage;              //@synthesize backdropMaskImage=_backdropMaskImage - In the implementation block
-(void)setBackdropMaskImage:(UIImage *)arg1 ;
-(UIImage *)backdropMaskImage;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

