/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UIView.h>

@class SCATModernMenuBackgroundView;

@interface SCATModernMenuView : UIView {

	SCATModernMenuBackgroundView* _backgroundView;

}

@property (nonatomic,retain) SCATModernMenuBackgroundView * backgroundView;              //@synthesize backgroundView=_backgroundView - In the implementation block
-(CGSize)sizeThatFits:(CGSize)arg1 includeTip:(BOOL)arg2 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setBackgroundView:(SCATModernMenuBackgroundView *)arg1 ;
-(SCATModernMenuBackgroundView *)backgroundView;
@end

