/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATAxisLayer.h>

@class SCATXYAxisLineLayer;

@interface SCATXYAxisRangeLayer : SCATAxisLayer {

	SCATXYAxisLineLayer* _lineLayer;

}

@property (nonatomic,retain) SCATXYAxisLineLayer * lineLayer;              //@synthesize lineLayer=_lineLayer - In the implementation block
-(id)initWithAxis:(int)arg1 ;
-(void)updateTheme:(int)arg1 animated:(BOOL)arg2 ;
-(void)updateFrameForParentBounds:(CGRect)arg1 refinementPoint:(CGPoint*)arg2 ;
-(void)updateToFitWithinParentBounds:(CGRect)arg1 ;
-(id)_backgroundColorForTheme:(int)arg1 ;
-(void)setLineLayer:(SCATXYAxisLineLayer *)arg1 ;
-(id)_borderBackgroundColorForTheme:(int)arg1 ;
-(id)_borderForegroundColorForTheme:(int)arg1 ;
-(void)dealloc;
-(void)removeAllAnimations;
-(SCATXYAxisLineLayer *)lineLayer;
@end

