/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <AXRuntime/AXElementGroup.h>

@protocol SCATPointPickerGroupDelegate;
@class NSIndexPath;

@interface SCATPointPickerGroup : AXElementGroup {

	id<SCATPointPickerGroupDelegate> _delegate;
	NSIndexPath* _selectionPath;

}

@property (assign,nonatomic) id<SCATPointPickerGroupDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSIndexPath * selectionPath;                          //@synthesize selectionPath=_selectionPath - In the implementation block
-(CGRect)scatFrame;
-(NSIndexPath *)selectionPath;
-(id)initWithSelectionPath:(id)arg1 generatorDelegate:(id)arg2 ;
-(BOOL)scatIsValid;
-(void)setDelegate:(id<SCATPointPickerGroupDelegate>)arg1 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id<SCATPointPickerGroupDelegate>)delegate;
@end

