/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATDriver.h>

@interface SCATDwellDriver : SCATDriver {

	BOOL _isReadyForSelect;

}

@property (assign,nonatomic) BOOL isReadyForSelect;              //@synthesize isReadyForSelect=_isReadyForSelect - In the implementation block
-(void)_idleTimerDidFire;
-(int)driverType;
-(BOOL)_handleStepNextAction;
-(BOOL)_handleStepPreviousAction;
-(void)_didTransitionToPhase:(int)arg1 ;
-(BOOL)_handleSelectAction;
-(BOOL)handleInputAction:(long long)arg1 ;
-(void)_resetDwellTimer;
-(BOOL)isReadyForSelect;
-(BOOL)_actuallyHandleSelectAction;
-(BOOL)_shouldUseDwellSelection;
-(BOOL)_handleStepAction:(long long)arg1 ;
-(void)_startDwellTimer;
-(void)_cancelDwellRelatedTimers;
-(void)_dwellTimerFired;
-(void)setIsReadyForSelect:(BOOL)arg1 ;
-(void)_scanAbortTimerFired;
-(BOOL)_shouldUseScanAbortTimer;
-(void)_startScanAbortTimer;
@end

