/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCATGestureProviderDelegate <NSObject>
@required
-(id)contentViewForGestureProvider:(id)arg1;
-(void)gestureProvider:(id)arg1 didShowFingers:(BOOL)arg2;
-(void)didChooseCreateCustomGestureFromGestureProvider:(id)arg1;
-(void)gestureProvider:(id)arg1 shouldResetScanningFromElement:(id)arg2;
-(void)shouldStartScanningGestureProvider:(id)arg1;
-(void)shouldEndScanningGestureProvider:(id)arg1;

@end

