/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATSimpleElementManager.h>

@protocol SCATCandidateBarManagerDelegate;
@class NSArray;

@interface SCATCandidateBarManager : SCATSimpleElementManager {

	id<SCATCandidateBarManagerDelegate> _delegate;
	NSArray* _typingCandidates;

}

@property (assign,nonatomic) id<SCATCandidateBarManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSArray * typingCandidates;                                //@synthesize typingCandidates=_typingCandidates - In the implementation block
-(void)driver:(id)arg1 willFocusOnContext:(id)arg2 ;
-(BOOL)handleInputAction:(long long)arg1 withElement:(id)arg2 ;
-(void)setTypingCandidates:(NSArray *)arg1 ;
-(BOOL)canBeActiveElementManager;
-(id)allElements;
-(void)didFetchElements:(id)arg1 foundNewElements:(BOOL)arg2 currentFocusContext:(id)arg3 didChangeActiveElementManager:(BOOL)arg4 ;
-(void)setDelegate:(id<SCATCandidateBarManagerDelegate>)arg1 ;
-(void)dealloc;
-(id<SCATCandidateBarManagerDelegate>)delegate;
-(NSArray *)typingCandidates;
@end

