/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATInputSource.h>
#import <assistivetouchd/AXEventHandler.h>

@protocol SCATScreenInputSourceDelegate;
@class AXAccessQueue, NSString;

@interface SCATScreenInputSource : SCATInputSource <AXEventHandler> {

	id<SCATScreenInputSourceDelegate> _delegate;
	AXAccessQueue* _queue;

}

@property (assign,nonatomic) id<SCATScreenInputSourceDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) AXAccessQueue * queue;                                   //@synthesize queue=_queue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)handledEvent:(id)arg1 ;
-(id)actionsForSwitches:(id)arg1 withRecipe:(id)arg2 ;
-(void)_didReceiveActionWithIdentifier:(long long)arg1 start:(BOOL)arg2 ignoreInputHold:(BOOL)arg3 ;
-(long long)_actionIdentifierWithType:(NSString*)arg1 ;
-(void)_startHandlingEvents;
-(void)_stopHandlingEvents;
-(void)setDelegate:(id<SCATScreenInputSourceDelegate>)arg1 ;
-(void)dealloc;
-(id<SCATScreenInputSourceDelegate>)delegate;
-(unsigned long long)priority;
-(AXAccessQueue *)queue;
-(void)setDelegate:(id)arg1 queue:(id)arg2 ;
-(void)setQueue:(AXAccessQueue *)arg1 ;
-(void)startRunning;
-(void)stopRunning;
@end

