/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UIView.h>

@class SCATModernMenuPageControl;

@interface SCATModernMenuFooterView : UIView {

	SCATModernMenuPageControl* _moreItemsPageControl;

}

@property (nonatomic,retain) SCATModernMenuPageControl * moreItemsPageControl;              //@synthesize moreItemsPageControl=_moreItemsPageControl - In the implementation block
-(SCATModernMenuPageControl *)moreItemsPageControl;
-(void)setMoreItemsPageControl:(SCATModernMenuPageControl *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

