/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuGestureFreehandSheetBase.h>

@class NSString;

@interface SCATModernMenuGestureFreehandStopSheet : SCATModernMenuGestureFreehandSheetBase {

	NSString* _actionToStop;

}

@property (nonatomic,copy) NSString * actionToStop;              //@synthesize actionToStop=_actionToStop - In the implementation block
-(void)menuItemWasActivated:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(NSString *)actionToStop;
-(BOOL)allowsBackAction;
-(BOOL)allowsExitAction;
-(BOOL)shouldAllowDwellSelection;
-(void)setActionToStop:(NSString *)arg1 ;
-(void)dealloc;
@end

