/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATSimpleElement.h>

@class NSIndexPath;

@interface SCATPointPickerElement : SCATSimpleElement {

	NSIndexPath* _selectionPath;

}

@property (nonatomic,readonly) NSIndexPath * selectionPath;              //@synthesize selectionPath=_selectionPath - In the implementation block
-(NSIndexPath *)selectionPath;
-(id)initWithSelectionPath:(id)arg1 ;
-(void)dealloc;
@end

