/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuSheet.h>

@interface SCATModernMenuSettingsSheet : SCATModernMenuSheet
-(BOOL)shouldUpdateMenuItem:(id)arg1 ;
-(void)menuItemWasActivated:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(id)initWithMenu:(id)arg1 ;
-(long long)scanningMode;
-(long long)preferredPointPicker;
-(void)togglePointMode;
-(void)_title:(id*)arg1 imageForPointPickerItem:(id*)arg2 ;
@end

