/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATAxisLayer.h>

@interface SCATXYAxisLineLayer : SCATAxisLayer

@property (nonatomic,readonly) BOOL isActive; 
-(void)updateTheme:(int)arg1 animated:(BOOL)arg2 ;
-(id)_foregroundColorForTheme:(int)arg1 ;
-(id)_backgroundColorForTheme:(int)arg1 ;
-(BOOL)isActive;
@end

