/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UICollectionViewLayoutAttributes.h>

@interface SCATMenuLayoutAttributes : UICollectionViewLayoutAttributes {

	unsigned long long row;
	unsigned long long column;
	double titleTextHeight;

}

@property (assign,nonatomic) unsigned long long row; 
@property (assign,nonatomic) unsigned long long column; 
@property (assign,nonatomic) double titleTextHeight; 
-(double)titleTextHeight;
-(void)setTitleTextHeight:(double)arg1 ;
-(unsigned long long)row;
-(id)description;
-(unsigned long long)column;
-(void)setRow:(unsigned long long)arg1 ;
-(void)setColumn:(unsigned long long)arg1 ;
@end

