/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATPointPickerViewController.h>
#import <assistivetouchd/SCATPointPickerSquareDelegate.h>
#import <assistivetouchd/SCATPointPickerGroupDelegate.h>
#import <assistivetouchd/SCATPointPickerCenterPointDelegate.h>

@class NSMutableDictionary, SCATGridPointPickerView, NSIndexPath, NSString;

@interface SCATGridPointPickerViewController : SCATPointPickerViewController <SCATPointPickerSquareDelegate, SCATPointPickerGroupDelegate, SCATPointPickerCenterPointDelegate> {

	NSMutableDictionary* _scannableElements;

}

@property (nonatomic,readonly) SCATGridPointPickerView * pointPickerView; 
@property (nonatomic,retain) NSIndexPath * currentSelectionPath; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)driver:(id)arg1 didFocusOnContext:(id)arg2 ;
-(id)lastElementWithOptions:(int*)arg1 ;
-(id)firstElementWithOptions:(int*)arg1 ;
-(BOOL)handleInputAction:(long long)arg1 withElement:(id)arg2 ;
-(NSIndexPath *)currentSelectionPath;
-(void)setCurrentSelectionPath:(NSIndexPath *)arg1 ;
-(id)elementAfter:(id)arg1 didWrap:(BOOL*)arg2 options:(int*)arg3 ;
-(id)elementBefore:(id)arg1 didWrap:(BOOL*)arg2 options:(int*)arg3 ;
-(void)scannerWillMakeManagerActive:(id)arg1 ;
-(void)scannerWillMakeManagerInactive:(id)arg1 ;
-(CGRect)scannerFrameForPointPickerSquare:(id)arg1 ;
-(CGRect)scannerFrameForPointPickerGroup:(id)arg1 ;
-(CGRect)scannerFrameForPointPickerCenterPoint:(id)arg1 ;
-(CGPathRef)scannerPathForPointPickerCenterPoint:(id)arg1 ;
-(BOOL)_showsRowsForSelectionPath:(id)arg1 ;
-(SCATGridPointPickerView *)pointPickerView;
-(id)_scannableElementsAtSelectionPath:(id)arg1 ;
-(id)_scannableElements;
-(void)_resetGrid;
-(Class)classForPointPickerView;
-(void)dealloc;
-(NSString *)description;
-(id)generateElementsForGroup:(id)arg1 ;
-(void)didGenerateElements:(id)arg1 ;
-(BOOL)_isVisible;
@end

