/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATHardwareInputSource.h>

@class NSString;

@interface SCATMFIInputSource : SCATHardwareInputSource {

	NSString* _productName;
	NSString* _serialNumber;
	NSString* _manufacturerName;
	NSString* _versionNumber;
	long long _availableButtons;

}

@property (nonatomic,retain) NSString * productName;                   //@synthesize productName=_productName - In the implementation block
@property (nonatomic,retain) NSString * serialNumber;                  //@synthesize serialNumber=_serialNumber - In the implementation block
@property (nonatomic,retain) NSString * manufacturerName;              //@synthesize manufacturerName=_manufacturerName - In the implementation block
@property (nonatomic,retain) NSString * versionNumber;                 //@synthesize versionNumber=_versionNumber - In the implementation block
@property (assign,nonatomic) long long availableButtons;               //@synthesize availableButtons=_availableButtons - In the implementation block
-(BOOL)isMFIInputSource;
-(long long)availableButtons;
-(long long)_switchKeyForSwitch:(id)arg1 ;
-(NSString*)_switchSource;
-(void)setVersionNumber:(NSString *)arg1 ;
-(long long)_actionIdentifierForButtonNumber:(long long)arg1 withType:(NSString*)arg2 ;
-(void)setAvailableButtons:(long long)arg1 ;
-(NSString *)versionNumber;
-(void)dealloc;
-(NSString *)productName;
-(void)setProductName:(NSString *)arg1 ;
-(void)setManufacturerName:(NSString *)arg1 ;
-(NSString *)serialNumber;
-(BOOL)isAvailable;
-(void)setSerialNumber:(NSString *)arg1 ;
-(NSString *)manufacturerName;
@end

