/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATInputSource.h>
#import <assistivetouchd/AVCaptureMetadataOutputObjectsDelegate.h>
#import <assistivetouchd/AVCaptureVideoDataOutputSampleBufferDelegate.h>

@protocol SCATCameraInputSourceDelegate, OS_dispatch_queue;
@class AXAccessQueue, NSObject, AVCaptureSession, UIView, AVCaptureVideoPreviewLayer, CALayer, NSString;

@interface SCATCameraInputSource : SCATInputSource <AVCaptureMetadataOutputObjectsDelegate, AVCaptureVideoDataOutputSampleBufferDelegate> {

	BOOL _available;
	BOOL _leftHeadSwitchDown;
	BOOL _rightHeadSwitchDown;
	id<SCATCameraInputSourceDelegate> _delegate;
	AXAccessQueue* _queue;
	NSObject*<OS_dispatch_queue> _captureOutputQueue;
	AVCaptureSession* _captureSession;
	unsigned long long _availabilityDetail;
	SCD_Struct_SC16* _face;
	UIView* _captureOutputPreview;
	AVCaptureVideoPreviewLayer* _captureVideoPreviewLayer;
	CALayer* _faceLayer;
	CGPoint _state;

}

@property (assign,getter=isAvailable,nonatomic) BOOL available;                                  //@synthesize available=_available - In the implementation block
@property (assign,nonatomic) CGPoint state;                                                      //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) id<SCATCameraInputSourceDelegate> delegate;                         //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) AXAccessQueue * queue;                                              //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> captureOutputQueue;                    //@synthesize captureOutputQueue=_captureOutputQueue - In the implementation block
@property (nonatomic,retain) AVCaptureSession * captureSession;                                  //@synthesize captureSession=_captureSession - In the implementation block
@property (assign,nonatomic) unsigned long long availabilityDetail;                              //@synthesize availabilityDetail=_availabilityDetail - In the implementation block
@property (assign,nonatomic) SCD_Struct_SC16* face;                                              //@synthesize face=_face - In the implementation block
@property (assign,getter=isLeftHeadSwitchDown,nonatomic) BOOL leftHeadSwitchDown;                //@synthesize leftHeadSwitchDown=_leftHeadSwitchDown - In the implementation block
@property (assign,getter=isRightHeadSwitchDown,nonatomic) BOOL rightHeadSwitchDown;              //@synthesize rightHeadSwitchDown=_rightHeadSwitchDown - In the implementation block
@property (nonatomic,retain) UIView * captureOutputPreview;                                      //@synthesize captureOutputPreview=_captureOutputPreview - In the implementation block
@property (nonatomic,retain) AVCaptureVideoPreviewLayer * captureVideoPreviewLayer;              //@synthesize captureVideoPreviewLayer=_captureVideoPreviewLayer - In the implementation block
@property (nonatomic,retain) CALayer * faceLayer;                                                //@synthesize faceLayer=_faceLayer - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)actionsForSwitches:(id)arg1 withRecipe:(id)arg2 ;
-(unsigned long long)availabilityDetail;
-(void)setAvailabilityDetail:(unsigned long long)arg1 ;
-(void)_didUpdateAvailability:(BOOL)arg1 withDetail:(unsigned long long)arg2 ;
-(void)setCaptureOutputQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(UIView *)captureOutputPreview;
-(void)setCaptureOutputPreview:(UIView *)arg1 ;
-(void)setFaceLayer:(CALayer *)arg1 ;
-(id)_captureSessionWithPreset:(id)arg1 ;
-(id)_captureDeviceInputWithPreset:(id)arg1 ;
-(id)_captureVideoDataOutputWithDelegate:(id)arg1 queue:(id)arg2 format:(id)arg3 ;
-(id)_captureMetadataOutputWithDelegate:(id)arg1 queue:(id)arg2 ;
-(BOOL)isLeftHeadSwitchDown;
-(long long)_actionIdentifierForHeadSwitch:(long long)arg1 ;
-(void)_didReceiveActionWithIdentifier:(long long)arg1 start:(BOOL)arg2 ;
-(void)setLeftHeadSwitchDown:(BOOL)arg1 ;
-(BOOL)isRightHeadSwitchDown;
-(void)setRightHeadSwitchDown:(BOOL)arg1 ;
-(void)_didUpdateState:(CGPoint)arg1 ;
-(CALayer *)faceLayer;
-(void)_cleanupCaptureOutput;
-(void)_setupCaptureOutput;
-(void)_startCaptureOutput;
-(void)_stopCaptureOutput;
-(NSObject*<OS_dispatch_queue>)captureOutputQueue;
-(void)setFace:(SCD_Struct_SC16*)arg1 ;
-(void)setDelegate:(id<SCATCameraInputSourceDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<SCATCameraInputSourceDelegate>)delegate;
-(CGPoint)state;
-(void)setState:(CGPoint)arg1 ;
-(AXAccessQueue *)queue;
-(SCD_Struct_SC16*)face;
-(void)setAvailable:(BOOL)arg1 ;
-(void)setDelegate:(id)arg1 queue:(id)arg2 ;
-(BOOL)isAvailable;
-(void)setQueue:(AXAccessQueue *)arg1 ;
-(void)setCaptureVideoPreviewLayer:(AVCaptureVideoPreviewLayer *)arg1 ;
-(void)startRunning;
-(AVCaptureVideoPreviewLayer *)captureVideoPreviewLayer;
-(void)stopRunning;
-(AVCaptureSession *)captureSession;
-(void)setCaptureSession:(AVCaptureSession *)arg1 ;
-(void)captureOutput:(id)arg1 didOutputSampleBuffer:(opaqueCMSampleBufferRef)arg2 fromConnection:(id)arg3 ;
-(void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3 ;
@end

