/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class SCATElementManager, SCATStyleProvider;

@interface SCATElementManagerViewController : UIViewController {

	SCATElementManager* _elementManager;

}

@property (assign,nonatomic) SCATElementManager * elementManager;              //@synthesize elementManager=_elementManager - In the implementation block
@property (nonatomic,readonly) SCATStyleProvider * styleProvider; 
-(void)didPresentWithDisplayContext:(id)arg1 animated:(BOOL)arg2 ;
-(void)didUpdateWithDisplayContext:(id)arg1 animated:(BOOL)arg2 ;
-(void)didDismiss:(BOOL)arg1 ;
-(SCATElementManager *)elementManager;
-(id)initWithElementManager:(id)arg1 ;
-(void)willPresentWithDisplayContext:(id)arg1 animated:(BOOL)arg2 ;
-(void)setElementManager:(SCATElementManager *)arg1 ;
-(void)presentWithDisplayContext:(id)arg1 animted:(BOOL)arg2 ;
-(void)willDismiss:(BOOL)arg1 ;
-(void)dealloc;
-(void)dismiss:(BOOL)arg1 ;
-(SCATStyleProvider *)styleProvider;
@end

