/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol SCATElement;
@class SCATElementManager, AXElementGroup;

@interface SCATFocusContext : NSObject <NSCopying> {

	BOOL _firstInSequence;
	BOOL _shouldResumeFromMenuDismissal;
	BOOL _shouldBeTrackedByZoom;
	BOOL _shouldSuppressAudioOutput;
	int _selectBehavior;
	id<SCATElement> _element;
	SCATElementManager* _elementManager;
	id<SCATElement> _menuElement;

}

@property (nonatomic,retain) id<SCATElement> element;                                    //@synthesize element=_element - In the implementation block
@property (assign,nonatomic) SCATElementManager * elementManager;                        //@synthesize elementManager=_elementManager - In the implementation block
@property (assign,nonatomic) int selectBehavior;                                         //@synthesize selectBehavior=_selectBehavior - In the implementation block
@property (assign,getter=isFirstInSequence,nonatomic) BOOL firstInSequence;              //@synthesize firstInSequence=_firstInSequence - In the implementation block
@property (assign,nonatomic) BOOL shouldResumeFromMenuDismissal;                         //@synthesize shouldResumeFromMenuDismissal=_shouldResumeFromMenuDismissal - In the implementation block
@property (nonatomic,retain) id<SCATElement> menuElement;                                //@synthesize menuElement=_menuElement - In the implementation block
@property (nonatomic,readonly) AXElementGroup * parentGroup; 
@property (nonatomic,readonly) BOOL isGroup; 
@property (assign,nonatomic) BOOL shouldBeTrackedByZoom;                                 //@synthesize shouldBeTrackedByZoom=_shouldBeTrackedByZoom - In the implementation block
@property (assign,nonatomic) BOOL shouldSuppressAudioOutput;                             //@synthesize shouldSuppressAudioOutput=_shouldSuppressAudioOutput - In the implementation block
+(id)focusContextWithElement:(id)arg1 elementManager:(id)arg2 selectBehavior:(int)arg3 options:(int)arg4 ;
+(id)adHocFocusContext:(id)arg1 ;
+(int)_behaviorForElement:(id)arg1 manager:(id)arg2 ;
+(id)focusContextSelf;
+(id)focusContextAutomatic;
+(id)menuOnlyFocusContext:(id)arg1 ;
-(SCATElementManager *)elementManager;
-(void)setFirstInSequence:(BOOL)arg1 ;
-(void)setShouldSuppressAudioOutput:(BOOL)arg1 ;
-(int)selectBehavior;
-(void)setMenuElement:(id<SCATElement>)arg1 ;
-(id<SCATElement>)menuElement;
-(BOOL)waitsForSelectAction;
-(BOOL)isFirstInSequence;
-(BOOL)shouldBeTrackedByZoom;
-(id)initWithElement:(id)arg1 elementManager:(id)arg2 selectBehavior:(int)arg3 ;
-(void)setShouldResumeFromMenuDismissal:(BOOL)arg1 ;
-(void)setSelectBehavior:(int)arg1 ;
-(void)setShouldBeTrackedByZoom:(BOOL)arg1 ;
-(void)setElementManager:(SCATElementManager *)arg1 ;
-(BOOL)shouldResumeFromMenuDismissal;
-(id)_descriptionForSelectBehavior:(int)arg1 ;
-(BOOL)shouldSuppressAudioOutput;
-(void)dealloc;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)containsPoint:(CGPoint)arg1 ;
-(BOOL)isGroup;
-(AXElementGroup *)parentGroup;
-(id<SCATElement>)element;
-(void)setElement:(id<SCATElement>)arg1 ;
@end

