/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCATMenuDelegate <NSObject>
@required
-(void)menu:(id)arg1 activateRecipe:(id)arg2;
-(CGRect*)menu:(id)arg1 rectToClearForFingersWithGestureSheet:(BOOL)arg2;
-(id)exitActionElementForFingersInMenu:(id)arg1;
-(BOOL)shouldShowAppWideScrollActionsInMenu:(id)arg1;
-(id)menu:(id)arg1 tapContextItemForSheet:(id)arg2;
-(id)menu:(id)arg1 tapAndHoldContextItemForSheet:(id)arg2;
-(BOOL)shouldAddItemSpecificMenuOptionsToMenu:(id)arg1;
-(long long)itemMenuStateForMenu:(id)arg1;
-(void)menu:(id)arg1 showTypingCandidates:(id)arg2;
-(id)gesturesSheetForMenu:(id)arg1;
-(void)menu:(id)arg1 showAlternateKeysForKey:(id)arg2;
-(void)menu:(id)arg1 setItemMenuState:(long long)arg2;
-(void)menu:(id)arg1 showScrollViewPickerForScrollViews:(id)arg2 elementsToScroll:(id)arg3 scrollAction:(int)arg4;
-(void)didPressScreenChangingButtonInMenu:(id)arg1;

@end

