/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UILabel.h>

@class UIColor;

@interface SCATOutlineLabel : UILabel {

	UIColor* _outlineColor;
	double _outlineThickness;

}

@property (nonatomic,retain) UIColor * outlineColor;               //@synthesize outlineColor=_outlineColor - In the implementation block
@property (assign,nonatomic) double outlineThickness;              //@synthesize outlineThickness=_outlineThickness - In the implementation block
-(double)outlineThickness;
-(void)setOutlineThickness:(double)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)drawTextInRect:(CGRect)arg1 ;
-(UIColor *)outlineColor;
-(void)setOutlineColor:(UIColor *)arg1 ;
@end

