/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCATMenuGeneralGestureItemsViewDelegate <SCATMenuGestureSheetViewDelegate>
@required
-(void)didChooseFavorites:(id)arg1;
-(void)didChoosePanGesture:(id)arg1;
-(void)didChooseFlickGesture:(id)arg1;
-(void)didChoosePinchGesture:(id)arg1;
-(void)didChooseDragGesture:(id)arg1;
-(void)didChooseDoubleTapGesture:(id)arg1;
-(void)didChooseHoldAndDragGesture:(id)arg1;
-(void)didChooseDrawingGesture:(id)arg1;
-(void)didChooseFingers:(id)arg1;
-(void)didChooseForceTouchGesture:(id)arg1;
-(id)tapGestureMenuItem:(id)arg1;
-(id)tapAndHoldGestureMenuItem:(id)arg1;
-(unsigned long long)numberOfFingers:(id)arg1;

@end

