/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATPointPicker.h>

@class SCATFocusContext;

@interface SCATXYAxisPointPicker : SCATPointPicker {

	SCATFocusContext* _sweepFocusContext;

}

@property (nonatomic,retain) SCATFocusContext * sweepFocusContext;              //@synthesize sweepFocusContext=_sweepFocusContext - In the implementation block
-(BOOL)isRefiningPoint;
-(void)didSweepOverPoint:(CGPoint)arg1 ;
-(void)setSweepFocusContext:(SCATFocusContext *)arg1 ;
-(BOOL)handleInputAction:(long long)arg1 withElement:(id)arg2 ;
-(BOOL)shouldKeepScannerAwake;
-(BOOL)providesElements;
-(id)initWithMenu:(id)arg1 ;
-(BOOL)allowsSelectionRefinement;
-(long long)pickerType;
-(SCATFocusContext *)sweepFocusContext;
-(void)dealloc;
-(void)orientationDidChange:(id)arg1 ;
@end

