/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuSheet.h>
#import <assistivetouchd/SCATModernMenuScrollSheetFallbackScrollAncestorDelegate.h>

@class AXUIElement, NSString;

@interface SCATModernMenuActionsSheet : SCATModernMenuSheet <SCATModernMenuScrollSheetFallbackScrollAncestorDelegate> {

	unsigned long long _storedNumberOfItemsInFirstPage;
	AXUIElement* _fallbackScrollDownAncestor;
	AXUIElement* _fallbackScrollUpAncestor;
	AXUIElement* _fallbackScrollLeftAncestor;
	AXUIElement* _fallbackScrollRightAncestor;

}

@property (assign,nonatomic) unsigned long long storedNumberOfItemsInFirstPage;              //@synthesize storedNumberOfItemsInFirstPage=_storedNumberOfItemsInFirstPage - In the implementation block
@property (nonatomic,retain) AXUIElement * fallbackScrollDownAncestor;                       //@synthesize fallbackScrollDownAncestor=_fallbackScrollDownAncestor - In the implementation block
@property (nonatomic,retain) AXUIElement * fallbackScrollUpAncestor;                         //@synthesize fallbackScrollUpAncestor=_fallbackScrollUpAncestor - In the implementation block
@property (nonatomic,retain) AXUIElement * fallbackScrollLeftAncestor;                       //@synthesize fallbackScrollLeftAncestor=_fallbackScrollLeftAncestor - In the implementation block
@property (nonatomic,retain) AXUIElement * fallbackScrollRightAncestor;                      //@synthesize fallbackScrollRightAncestor=_fallbackScrollRightAncestor - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)shouldUpdateMenuItem:(id)arg1 ;
-(void)menuItemWasActivated:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(id)initWithMenu:(id)arg1 ;
-(id)_typingCandidates;
-(long long)preferredTipObject;
-(void)setFallbackScrollDownAncestor:(AXUIElement *)arg1 ;
-(void)setFallbackScrollUpAncestor:(AXUIElement *)arg1 ;
-(void)setFallbackScrollLeftAncestor:(AXUIElement *)arg1 ;
-(void)setFallbackScrollRightAncestor:(AXUIElement *)arg1 ;
-(unsigned long long)storedNumberOfItemsInFirstPage;
-(id)_menuItemForScrollAction:(int)arg1 ;
-(id)_bestScrollMenuItemForScrollableElement:(id)arg1 ;
-(void)_title:(id*)arg1 imageForNavigationItem:(id*)arg2 ;
-(void)_addTapIfApplicableForElement:(id)arg1 toMenuItems:(id)arg2 ;
-(void)_addDeviceToMenuItems:(id)arg1 ;
-(void)_addEditIfApplicableForElement:(id)arg1 toMenuItems:(id)arg2 ;
-(void)_addElementSpecificActionsIfApplicableForElement:(id)arg1 toMenuItems:(id)arg2 ;
-(void)_addEscapeIfApplicableForElement:(id)arg1 toMenuItems:(id)arg2 ;
-(void)_addGesturesToMenuItems:(id)arg1 ;
-(void)_addHomeToMenuItems:(id)arg1 ;
-(void)_addIncrementDecrementIfApplicableForElement:(id)arg1 toMenuItems:(id)arg2 ;
-(void)_addNavigationModeToggleToMenuItems:(id)arg1 ;
-(void)_addRecipesToMenuItems:(id)arg1 ;
-(void)_addRefineSelectionIfApplicableToMenuItems:(id)arg1 ;
-(void)_addAppWideScrollIfApplicableToMenuItems:(id)arg1 ;
-(void)_addScrollIfApplicableForElement:(id)arg1 toMenuItems:(id)arg2 ;
-(void)_addSettingsToMenuItems:(id)arg1 ;
-(void)_addSideAppToMenuItems:(id)arg1 ;
-(void)_addItemMenuToMenuItems:(id)arg1 ;
-(void)_addLockItemMenuToMenuItems:(id)arg1 ;
-(void)_addScrollShortcutIfApplicableForElement:(id)arg1 toMenuItems:(id)arg2 ;
-(void)setStoredNumberOfItemsInFirstPage:(unsigned long long)arg1 ;
-(void)_performFallbackScrollAncestorAction:(int)arg1 ;
-(AXUIElement *)fallbackScrollUpAncestor;
-(AXUIElement *)fallbackScrollDownAncestor;
-(AXUIElement *)fallbackScrollLeftAncestor;
-(AXUIElement *)fallbackScrollRightAncestor;
-(void)_performScrollAction:(int)arg1 ;
-(void)toggleScanningMode;
-(void)scrollSheet:(id)arg1 performFallbackScrollAncestorAction:(int)arg2 ;
-(BOOL)scrollSheet:(id)arg1 shouldIncludeFallbackScrollAncestorActionsInVerticalDirection:(BOOL)arg2 ;
-(id)fallbackAncestorForScrollToTopInScrollSheet:(id)arg1 ;
-(id)fallbackAncestorForAutoscrollInScrollSheet:(id)arg1 ;
-(unsigned long long)numberOfItemsInFirstPage;
-(void)dealloc;
@end

