/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATCameraInputSourceDelegate.h>
#import <assistivetouchd/SCATHardwareInputSourceDelegate.h>
#import <assistivetouchd/SCATScreenInputSourceDelegate.h>

@protocol SCATInputControllerDelegate;
@class AXSwitchRecipe, AXAccessQueue, SCATCameraInputSource, SCATKeyboardInputSource, SCATMFIInputSource, SCATScreenInputSource, AXAccessQueueTimer, AXUIClient, NSString;

@interface SCATInputController : NSObject <SCATCameraInputSourceDelegate, SCATHardwareInputSourceDelegate, SCATScreenInputSourceDelegate> {

	BOOL _valid;
	BOOL _isInputHoldEnabled;
	BOOL _isInputRepeatEnabled;
	BOOL _isInputCoalesceEnabled;
	BOOL _hasInitializedInputSources;
	AXSwitchRecipe* _recipe;
	id<SCATInputControllerDelegate> _delegate;
	AXAccessQueue* _queue;
	SCATCameraInputSource* _cameraInputSource;
	SCATKeyboardInputSource* _keyboardInputSource;
	SCATMFIInputSource* _mfiInputSource;
	SCATScreenInputSource* _screenInputSource;
	double _timeIntervalBeforeSendAction;
	double _timeIntervalBeforeSendLongPressAction;
	double _timeIntervalBeforeSendRepeatAction;
	double _timeIntervalBetweenDidSendActions;
	double _timeIntervalSinceDidSendAction;
	AXAccessQueueTimer* _inputHoldTimer;
	AXAccessQueueTimer* _inputRepeatTimer;
	AXAccessQueueTimer* _inputLongPressTimer;

}

@property (nonatomic,retain) AXSwitchRecipe * recipe;                                    //@synthesize recipe=_recipe - In the implementation block
@property (assign,getter=isValid,nonatomic) BOOL valid;                                  //@synthesize valid=_valid - In the implementation block
@property (nonatomic,readonly) AXUIClient * userInterfaceClient; 
@property (assign,nonatomic) id<SCATInputControllerDelegate> delegate;                   //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) AXAccessQueue * queue;                                      //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) SCATCameraInputSource * cameraInputSource;                  //@synthesize cameraInputSource=_cameraInputSource - In the implementation block
@property (nonatomic,retain) SCATKeyboardInputSource * keyboardInputSource;              //@synthesize keyboardInputSource=_keyboardInputSource - In the implementation block
@property (nonatomic,retain) SCATMFIInputSource * mfiInputSource;                        //@synthesize mfiInputSource=_mfiInputSource - In the implementation block
@property (nonatomic,retain) SCATScreenInputSource * screenInputSource;                  //@synthesize screenInputSource=_screenInputSource - In the implementation block
@property (assign,nonatomic) double timeIntervalBeforeSendAction;                        //@synthesize timeIntervalBeforeSendAction=_timeIntervalBeforeSendAction - In the implementation block
@property (assign,nonatomic) double timeIntervalBeforeSendLongPressAction;               //@synthesize timeIntervalBeforeSendLongPressAction=_timeIntervalBeforeSendLongPressAction - In the implementation block
@property (assign,nonatomic) double timeIntervalBeforeSendRepeatAction;                  //@synthesize timeIntervalBeforeSendRepeatAction=_timeIntervalBeforeSendRepeatAction - In the implementation block
@property (assign,nonatomic) double timeIntervalBetweenDidSendActions;                   //@synthesize timeIntervalBetweenDidSendActions=_timeIntervalBetweenDidSendActions - In the implementation block
@property (assign,nonatomic) double timeIntervalSinceDidSendAction;                      //@synthesize timeIntervalSinceDidSendAction=_timeIntervalSinceDidSendAction - In the implementation block
@property (assign,nonatomic) BOOL isInputHoldEnabled;                                    //@synthesize isInputHoldEnabled=_isInputHoldEnabled - In the implementation block
@property (assign,nonatomic) BOOL isInputRepeatEnabled;                                  //@synthesize isInputRepeatEnabled=_isInputRepeatEnabled - In the implementation block
@property (assign,nonatomic) BOOL isInputCoalesceEnabled;                                //@synthesize isInputCoalesceEnabled=_isInputCoalesceEnabled - In the implementation block
@property (nonatomic,retain) AXAccessQueueTimer * inputHoldTimer;                        //@synthesize inputHoldTimer=_inputHoldTimer - In the implementation block
@property (nonatomic,retain) AXAccessQueueTimer * inputRepeatTimer;                      //@synthesize inputRepeatTimer=_inputRepeatTimer - In the implementation block
@property (nonatomic,retain) AXAccessQueueTimer * inputLongPressTimer;                   //@synthesize inputLongPressTimer=_inputLongPressTimer - In the implementation block
@property (assign,nonatomic) BOOL hasInitializedInputSources;                            //@synthesize hasInitializedInputSources=_hasInitializedInputSources - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)isSwitchWithSource:(NSString*)arg1 ;
-(id)_inputSourceForSwitchSource:(NSString*)arg1 ;
-(id)_allSwitchesInUse;
-(AXSwitchRecipe *)recipe;
-(SCATCameraInputSource *)cameraInputSource;
-(SCATKeyboardInputSource *)keyboardInputSource;
-(SCATScreenInputSource *)screenInputSource;
-(SCATMFIInputSource *)mfiInputSource;
-(BOOL)isInputCoalesceEnabled;
-(double)timeIntervalBetweenDidSendActions;
-(double)timeIntervalSinceDidSendAction;
-(void)setTimeIntervalSinceDidSendAction:(double)arg1 ;
-(void)_sendActionWithIdentifier:(long long)arg1 ;
-(BOOL)isInputHoldEnabled;
-(AXAccessQueueTimer *)inputHoldTimer;
-(double)timeIntervalBeforeSendAction;
-(void)_endAction;
-(AXAccessQueueTimer *)inputRepeatTimer;
-(BOOL)isInputRepeatEnabled;
-(double)timeIntervalBeforeSendRepeatAction;
-(void)setTimeIntervalBeforeSendAction:(double)arg1 ;
-(void)setTimeIntervalBeforeSendRepeatAction:(double)arg1 ;
-(void)setTimeIntervalBetweenDidSendActions:(double)arg1 ;
-(void)setIsInputHoldEnabled:(BOOL)arg1 ;
-(void)setIsInputRepeatEnabled:(BOOL)arg1 ;
-(void)setIsInputCoalesceEnabled:(BOOL)arg1 ;
-(void)_didReceiveActionWithIdentifier:(long long)arg1 start:(BOOL)arg2 ignoreInputHold:(BOOL)arg3 ;
-(void)_hideAlertForSource:(unsigned long long)arg1 ;
-(void)_showAlert:(id)arg1 forSource:(unsigned long long)arg2 ;
-(void)_showState:(id)arg1 forSource:(unsigned long long)arg2 ;
-(void)_configureMFIAccessoryIfNecessary:(id)arg1 ;
-(void)setCameraInputSource:(SCATCameraInputSource *)arg1 ;
-(void)_hideStateForSource:(unsigned long long)arg1 ;
-(void)setKeyboardInputSource:(SCATKeyboardInputSource *)arg1 ;
-(void)setMfiInputSource:(SCATMFIInputSource *)arg1 ;
-(void)setScreenInputSource:(SCATScreenInputSource *)arg1 ;
-(id)_actionsForSource:(NSString*)arg1 ;
-(void)updateWhetherSwitchConfigurationRendersDeviceUnusable;
-(void)_updateCameraInputSource;
-(void)_updateKeyboardInputSource;
-(void)_updateMFIInputSource;
-(void)_updateScreenInputSource;
-(void)setHasInitializedInputSources:(BOOL)arg1 ;
-(void)setInputHoldTimer:(AXAccessQueueTimer *)arg1 ;
-(void)setInputRepeatTimer:(AXAccessQueueTimer *)arg1 ;
-(void)_removeInputSources;
-(void)_removeInputTimers;
-(void)_updateTimeIntervalBeforeSendAction;
-(void)_updateIsInputHoldEnabled;
-(void)_updateTimeIntervalBeforeSendRepeatAction;
-(void)_updateIsInputRepeatEnabled;
-(void)_updateTimeIntervalBetweenDidSendActions;
-(void)_updateIsInputCoalesceEnabled;
-(void)_updateInputSources;
-(void)_setupInputTimers;
-(BOOL)hasInitializedInputSources;
-(BOOL)_switchConfigurationRendersDeviceUnusable;
-(AXUIClient *)userInterfaceClient;
-(void)cameraInputSource:(id)arg1 didReceiveActionWithIdentifier:(long long)arg2 start:(BOOL)arg3 ;
-(void)cameraInputSource:(id)arg1 didUpdateAvailability:(BOOL)arg2 withDetail:(unsigned long long)arg3 ;
-(void)cameraInputSource:(id)arg1 didUpdateState:(CGPoint)arg2 ;
-(void)hardwareInputSource:(id)arg1 didReceiveActionWithIdentifier:(long long)arg2 start:(BOOL)arg3 ignoreInputHold:(BOOL)arg4 ;
-(void)hardwareInputSource:(id)arg1 didUpdateAvailability:(BOOL)arg2 withDetail:(unsigned long long)arg3 ;
-(void)screenInputSource:(id)arg1 didReceiveActionWithIdentifier:(long long)arg2 start:(BOOL)arg3 ignoreInputHold:(BOOL)arg4 ;
-(void)setRecipe:(AXSwitchRecipe *)arg1 ;
-(double)timeIntervalBeforeSendLongPressAction;
-(void)setTimeIntervalBeforeSendLongPressAction:(double)arg1 ;
-(AXAccessQueueTimer *)inputLongPressTimer;
-(void)setInputLongPressTimer:(AXAccessQueueTimer *)arg1 ;
-(void)setDelegate:(id<SCATInputControllerDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<SCATInputControllerDelegate>)delegate;
-(BOOL)isValid;
-(AXAccessQueue *)queue;
-(void)setDelegate:(id)arg1 queue:(id)arg2 ;
-(void)setQueue:(AXAccessQueue *)arg1 ;
-(void)setValid:(BOOL)arg1 ;
@end

