/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UIView.h>

@protocol SCATGridDelegate;
@class UIImageView, UIColor;

@interface SCATGridView : UIView {

	UIImageView* _centerPoint;
	BOOL _showsTopBorder;
	BOOL _showsLeftBorder;
	BOOL _showsBottomBorder;
	BOOL _showsRightBorder;
	BOOL _centerPointVisible;
	BOOL _shouldIncludeCenterPoint;
	BOOL _shouldShowGridBorder;
	id<SCATGridDelegate> _delegate;
	unsigned long long _numberOfRows;
	unsigned long long _numberOfColumns;
	double _lineThickness;
	UIColor* _lineColor;
	UIColor* _shadowColor;
	CGSize _shadowOffset;

}

@property (assign,nonatomic) id<SCATGridDelegate> delegate;                                    //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) unsigned long long numberOfRows;                                  //@synthesize numberOfRows=_numberOfRows - In the implementation block
@property (assign,nonatomic) unsigned long long numberOfColumns;                               //@synthesize numberOfColumns=_numberOfColumns - In the implementation block
@property (assign,nonatomic) double lineThickness;                                             //@synthesize lineThickness=_lineThickness - In the implementation block
@property (nonatomic,retain) UIColor * lineColor;                                              //@synthesize lineColor=_lineColor - In the implementation block
@property (nonatomic,retain) UIColor * shadowColor;                                            //@synthesize shadowColor=_shadowColor - In the implementation block
@property (assign,nonatomic) CGSize shadowOffset;                                              //@synthesize shadowOffset=_shadowOffset - In the implementation block
@property (assign,nonatomic) BOOL showsTopBorder;                                              //@synthesize showsTopBorder=_showsTopBorder - In the implementation block
@property (assign,nonatomic) BOOL showsLeftBorder;                                             //@synthesize showsLeftBorder=_showsLeftBorder - In the implementation block
@property (assign,nonatomic) BOOL showsBottomBorder;                                           //@synthesize showsBottomBorder=_showsBottomBorder - In the implementation block
@property (assign,nonatomic) BOOL showsRightBorder;                                            //@synthesize showsRightBorder=_showsRightBorder - In the implementation block
@property (assign,getter=isCenterPointVisible,nonatomic) BOOL centerPointVisible;              //@synthesize centerPointVisible=_centerPointVisible - In the implementation block
@property (assign,nonatomic) BOOL shouldIncludeCenterPoint;                                    //@synthesize shouldIncludeCenterPoint=_shouldIncludeCenterPoint - In the implementation block
@property (assign,nonatomic) BOOL shouldShowGridBorder;                                        //@synthesize shouldShowGridBorder=_shouldShowGridBorder - In the implementation block
-(void)setShouldIncludeCenterPoint:(BOOL)arg1 ;
-(BOOL)shouldIncludeCenterPoint;
-(BOOL)showsTopBorder;
-(BOOL)showsBottomBorder;
-(double)_adjustOriginValue:(double)arg1 forDistance:(double)arg2 maximumEndPosition:(double)arg3 ;
-(void)_drawLinesInContext:(CGContextRef)arg1 forRows:(BOOL)arg2 ;
-(void)setShowsTopBorder:(BOOL)arg1 ;
-(void)setShowsBottomBorder:(BOOL)arg1 ;
-(void)setCenterPointVisible:(BOOL)arg1 ;
-(BOOL)isCenterPointVisible;
-(BOOL)shouldShowGridBorder;
-(void)setShouldShowGridBorder:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setDelegate:(id<SCATGridDelegate>)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(unsigned long long)numberOfColumns;
-(id<SCATGridDelegate>)delegate;
-(void)setShadowColor:(UIColor *)arg1 ;
-(void)setShadowOffset:(CGSize)arg1 ;
-(CGSize)shadowOffset;
-(UIColor *)shadowColor;
-(unsigned long long)numberOfRows;
-(void)setNumberOfRows:(unsigned long long)arg1 ;
-(void)setNumberOfColumns:(unsigned long long)arg1 ;
-(void)setLineThickness:(double)arg1 ;
-(double)lineThickness;
-(void)setShowsLeftBorder:(BOOL)arg1 ;
-(BOOL)showsLeftBorder;
-(void)setShowsRightBorder:(BOOL)arg1 ;
-(BOOL)showsRightBorder;
-(void)setLineColor:(UIColor *)arg1 ;
-(UIColor *)lineColor;
@end

