/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATDriver.h>

@class AXAccessQueueTimer;

@interface SCATAutomaticDriver : SCATDriver {

	BOOL _isSpeakingFocusContext;
	AXAccessQueueTimer* _focusTimer;
	long long _currentCycleCount;

}

@property (nonatomic,readonly) double focusInterval; 
@property (nonatomic,readonly) unsigned long long maxAutoscanCycles; 
@property (nonatomic,retain) AXAccessQueueTimer * focusTimer;                     //@synthesize focusTimer=_focusTimer - In the implementation block
@property (assign,nonatomic) long long currentCycleCount;                         //@synthesize currentCycleCount=_currentCycleCount - In the implementation block
@property (assign,nonatomic) BOOL isSpeakingFocusContext;                         //@synthesize isSpeakingFocusContext=_isSpeakingFocusContext - In the implementation block
-(void)_idleTimerDidFire;
-(int)driverType;
-(void)_didTransitionToPhase:(int)arg1 ;
-(void)_didWrapInDirection:(long long)arg1 ;
-(void)_willStepToNextFocusContext:(id)arg1 inDirection:(long long)arg2 ;
-(void)willDrillIntoGroup;
-(void)willDrillOutOfGroup;
-(BOOL)_handleRunAction;
-(BOOL)_handleSelectAction;
-(BOOL)_handleStopAction;
-(void)freezeScanning;
-(void)willFinishAsScannerDriver;
-(void)outputManager:(id)arg1 willSpeakFocusContext:(id)arg2 ;
-(void)outputManager:(id)arg1 didSpeakFocusContext:(id)arg2 ;
-(void)actionHandlerDidFireAction:(id)arg1 ;
-(void)actionHandlerDidCancelPendingAction:(id)arg1 ;
-(void)setFocusTimer:(AXAccessQueueTimer *)arg1 ;
-(long long)currentCycleCount;
-(AXAccessQueueTimer *)focusTimer;
-(void)_endAutoscanning;
-(void)setCurrentCycleCount:(long long)arg1 ;
-(void)_autoscanToNextFocusContext;
-(double)focusInterval;
-(BOOL)isSpeakingFocusContext;
-(void)setIsSpeakingFocusContext:(BOOL)arg1 ;
-(BOOL)_shouldPauseOnIdleTimer;
-(unsigned long long)maxAutoscanCycles;
-(void)dealloc;
-(id)description;
-(id)initWithDelegate:(id)arg1 ;
@end

