/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <QuartzCore/CABasicAnimation.h>

@class SCATAxisLayer, NSString;

@interface SCATSweepAnimation : CABasicAnimation {

	BOOL _forwardDirection;
	SCATAxisLayer* _scatLayer;
	NSString* _animationKey;

}

@property (assign,nonatomic) BOOL forwardDirection;                  //@synthesize forwardDirection=_forwardDirection - In the implementation block
@property (assign,nonatomic) SCATAxisLayer * scatLayer;              //@synthesize scatLayer=_scatLayer - In the implementation block
@property (nonatomic,copy) NSString * animationKey;                  //@synthesize animationKey=_animationKey - In the implementation block
+(id)sweepAnimationWithDirection:(BOOL)arg1 scatLayer:(id)arg2 animationKey:(id)arg3 ;
-(NSString *)animationKey;
-(SCATAxisLayer *)scatLayer;
-(id)reversedAnimation;
-(BOOL)forwardDirection;
-(void)setForwardDirection:(BOOL)arg1 ;
-(void)setScatLayer:(SCATAxisLayer *)arg1 ;
-(void)_updateAnimationKeyWithPrefix:(id)arg1 direction:(BOOL)arg2 ;
-(void)setAnimationKey:(NSString *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

