/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <assistivetouchd/assistivetouchd-Structs.h>
@class UIImage;

@interface SCATStyleProvider : NSObject {

	CGImageRef _bezelItemBackgroundImage;
	CGImageRef _bezelItemSelectedBackgroundImage;
	UIImage* _cachedGridCenterPointImage;

}
+(id)sharedStyleProvider;
+(long long)theme;
-(double)cursorContainerOpacity;
-(double)cursorHighVisibilityMultiplier;
-(double)cursorForegroundBorderWidth;
-(double)cursorBackgroundBorderWidth;
-(id)menuKnockoutColor;
-(double)menuKnockoutBorderOpacity;
-(long long)menuKnockoutBorderOverlayBlendMode;
-(double)gridLineThickness;
-(id)gridColor;
-(id)gridShadowColor;
-(CGSize)gridShadowOffset;
-(CGRect)gridCenterPointFrameWithAvailableFrame:(CGRect)arg1 ;
-(CGPathRef)gridCenterPointPathWithAvailableFrame:(CGRect)arg1 ;
-(id)gridCenterPointImageWithAvailableSize:(CGSize)arg1 ;
-(double)arrowHeadBaseOffset;
-(double)grayFingerOuterRadius;
-(double)controlArrowHeadSmallSideLength;
-(double)controlArrowHeadLargeSideLength;
-(double)controlArrowOutlineThickness;
-(double)controlArrowThickness;
-(id)controlArrowOutlineColor;
-(double)grayFingerInnerRadius;
-(id)controlArrowHighlightedColor;
-(id)controlArrowColor;
-(id)grayFingerInnerFill;
-(double)grayFingerInnerCircleOuterRadius;
-(double)grayFingerInnerCircleInnerRadius;
-(id)previewColor;
-(double)previewOutlineThickness;
-(id)previewOutlineColor;
-(double)arrowHeadBaseAngle;
-(double)arrowHeadBaseRadius;
-(double)previewLineThickness;
-(double)arrowHeadTipOffset;
-(long long)pointPickerPromptBackdropStyle;
-(id)pointPickerPromptTextColor;
-(id)pointPickerPromptFont;
-(double)pointPickerPromptCornerRadius;
-(double)pointPickerPromptPadding;
-(double)menuPageControlHighlightedBorderLineWidth;
-(id)menuPageControlHighlightedBorderColor;
-(id)scannerBlueColor;
-(id)rotation90ControlFont;
-(double)rotation90ControlNearestRadius;
-(double)rotationControlAngleAwayFromMidAngle;
-(double)rotationControlLength;
-(double)rotationControlCurveRadius;
-(void)unloadResources;
-(BOOL)_useVibrantBlendMode;
-(double)scannerCursorOutlineThickness;
-(void)_drawCrosshairWithSize:(CGSize)arg1 lineThickness:(double)arg2 ;
-(double)scannerCursorThickness;
-(double)cursorRoundedRectCornerRadius;
-(double)cursorElementPadding;
-(double)_gridImageShadowBlur;
-(double)minimumGridSquareWidth;
-(id)previewShadowColor;
-(double)previewShadowBlur;
-(CGSize)previewShadowOffset;
-(CGImageRef)bezelItemBackgroundImage;
-(CGImageRef)bezelItemSelectedBackgroundImage;
-(CGRect)bezelItemBackgroundImageContentsCenter;
-(void)dealloc;
@end

