/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATDriverDelegate.h>
#import <assistivetouchd/HNDAccessibilityManagerObserver.h>
#import <assistivetouchd/SCATInputControllerDelegate.h>
#import <assistivetouchd/SCATMenuDelegate.h>
#import <assistivetouchd/SCATMenuObserver.h>
#import <assistivetouchd/SCATGestureProviderDelegate.h>
#import <assistivetouchd/SCATPointPickerDelegate.h>
#import <assistivetouchd/SCATCursorManagerDelegate.h>
#import <assistivetouchd/SCATAlternateKeysManagerDelegate.h>
#import <assistivetouchd/SCATActionHandlerDelegate.h>
#import <assistivetouchd/SCATActionHandlerUIDelegate.h>
#import <assistivetouchd/SCATCandidateBarManagerDelegate.h>
#import <assistivetouchd/HNDElementNavigationControllerDelegate.h>
#import <assistivetouchd/SCATDisplaySource.h>

@class AXOutputManager, SCATCursorManager, AXDispatchTimer, HNDScannerAutoscroller, SCATInputController, SCATGestureProvider, SCATMenu, SCATPointPicker, HNDElementNavigationController, SCATManualDriver, SCATAutomaticDriver, SCATDriver, SCATElementManager, SCATActionHandler, SCATAlternateKeysManager, SCATScrollViewPickerManager, SCATCandidateBarManager, SCATDwellDriver, AXUIClient, SCATFocusContext, NSMutableSet, AXSwitchRecipe, NSString;

@interface SCATScannerManager : NSObject <SCATDriverDelegate, HNDAccessibilityManagerObserver, SCATInputControllerDelegate, SCATMenuDelegate, SCATMenuObserver, SCATGestureProviderDelegate, SCATPointPickerDelegate, SCATCursorManagerDelegate, SCATAlternateKeysManagerDelegate, SCATActionHandlerDelegate, SCATActionHandlerUIDelegate, SCATCandidateBarManagerDelegate, HNDElementNavigationControllerDelegate, SCATDisplaySource> {

	BOOL _isLoaded;
	BOOL _forceDisableScreenLock;
	BOOL _didSetFocusContextForResume;
	BOOL _didPauseForReasonsToDisableScanning;
	AXOutputManager* _outputManager;
	SCATCursorManager* _cursorManager;
	AXDispatchTimer* _beginScanningTimer;
	HNDScannerAutoscroller* _autoscroller;
	SCATInputController* _inputController;
	SCATGestureProvider* _gestureProvider;
	SCATMenu* _menu;
	SCATPointPicker* _pointPicker;
	HNDElementNavigationController* _elementNavController;
	SCATManualDriver* _manualScanningDriver;
	SCATAutomaticDriver* _autoScanningDriver;
	SCATDriver* _activeScannerDriver;
	SCATElementManager* _activeElementManager;
	SCATActionHandler* _selectActionHandler;
	SCATAlternateKeysManager* _alternateKeysManager;
	SCATScrollViewPickerManager* _scrollViewPickerManager;
	SCATCandidateBarManager* _candidateBarManager;
	SCATDwellDriver* _dwellScanningDriver;
	AXUIClient* _userInterfaceClient;
	SCATFocusContext* _focusContextForResume;
	NSMutableSet* _reasonsToDisableScanning;
	AXSwitchRecipe* _currentRecipe;
	long long _itemMenuState;

}

@property (nonatomic,readonly) BOOL isLoaded; 
@property (nonatomic,retain) SCATElementManager * activeElementManager;                          //@synthesize activeElementManager=_activeElementManager - In the implementation block
@property (nonatomic,retain) SCATDriver * activeScannerDriver;                                   //@synthesize activeScannerDriver=_activeScannerDriver - In the implementation block
@property (nonatomic,retain) HNDScannerAutoscroller * autoscroller;                              //@synthesize autoscroller=_autoscroller - In the implementation block
@property (nonatomic,retain) SCATMenu * menu;                                                    //@synthesize menu=_menu - In the implementation block
@property (nonatomic,retain) SCATPointPicker * pointPicker;                                      //@synthesize pointPicker=_pointPicker - In the implementation block
@property (nonatomic,retain) SCATCursorManager * cursorManager;                                  //@synthesize cursorManager=_cursorManager - In the implementation block
@property (nonatomic,readonly) BOOL isAutoscanEnabled; 
@property (nonatomic,readonly) BOOL isGroupingEnabled; 
@property (nonatomic,readonly) long long scanningMode; 
@property (nonatomic,readonly) BOOL areSoundEffectsEnabled; 
@property (nonatomic,readonly) BOOL isSpeechEnabled; 
@property (nonatomic,readonly) unsigned long long immediateSelectActionCount; 
@property (nonatomic,readonly) BOOL isLandscape; 
@property (nonatomic,readonly) BOOL shouldBypassShowingMenu; 
@property (nonatomic,readonly) BOOL isUsingPointMode; 
@property (nonatomic,readonly) BOOL isActive; 
@property (nonatomic,readonly) BOOL isPaused; 
@property (nonatomic,readonly) BOOL isInactive; 
@property (nonatomic,retain) SCATActionHandler * selectActionHandler;                            //@synthesize selectActionHandler=_selectActionHandler - In the implementation block
@property (nonatomic,retain) HNDElementNavigationController * elementNavController;              //@synthesize elementNavController=_elementNavController - In the implementation block
@property (nonatomic,retain) SCATAlternateKeysManager * alternateKeysManager;                    //@synthesize alternateKeysManager=_alternateKeysManager - In the implementation block
@property (nonatomic,retain) SCATScrollViewPickerManager * scrollViewPickerManager;              //@synthesize scrollViewPickerManager=_scrollViewPickerManager - In the implementation block
@property (nonatomic,retain) SCATCandidateBarManager * candidateBarManager;                      //@synthesize candidateBarManager=_candidateBarManager - In the implementation block
@property (nonatomic,readonly) SCATFocusContext * currentFocusContext; 
@property (nonatomic,readonly) id<SCATElement> currentElement; 
@property (nonatomic,retain) SCATAutomaticDriver * autoScanningDriver;                           //@synthesize autoScanningDriver=_autoScanningDriver - In the implementation block
@property (nonatomic,retain) SCATManualDriver * manualScanningDriver;                            //@synthesize manualScanningDriver=_manualScanningDriver - In the implementation block
@property (nonatomic,retain) SCATDwellDriver * dwellScanningDriver;                              //@synthesize dwellScanningDriver=_dwellScanningDriver - In the implementation block
@property (nonatomic,retain) SCATInputController * inputController;                              //@synthesize inputController=_inputController - In the implementation block
@property (nonatomic,retain) SCATGestureProvider * gestureProvider;                              //@synthesize gestureProvider=_gestureProvider - In the implementation block
@property (nonatomic,retain) AXOutputManager * outputManager;                                    //@synthesize outputManager=_outputManager - In the implementation block
@property (nonatomic,retain) AXUIClient * userInterfaceClient;                                   //@synthesize userInterfaceClient=_userInterfaceClient - In the implementation block
@property (nonatomic,retain) AXDispatchTimer * beginScanningTimer;                               //@synthesize beginScanningTimer=_beginScanningTimer - In the implementation block
@property (assign,nonatomic) BOOL forceDisableScreenLock;                                        //@synthesize forceDisableScreenLock=_forceDisableScreenLock - In the implementation block
@property (nonatomic,retain) SCATFocusContext * focusContextForResume;                           //@synthesize focusContextForResume=_focusContextForResume - In the implementation block
@property (assign,nonatomic) BOOL didSetFocusContextForResume;                                   //@synthesize didSetFocusContextForResume=_didSetFocusContextForResume - In the implementation block
@property (nonatomic,retain) NSMutableSet * reasonsToDisableScanning;                            //@synthesize reasonsToDisableScanning=_reasonsToDisableScanning - In the implementation block
@property (assign,nonatomic) BOOL didPauseForReasonsToDisableScanning;                           //@synthesize didPauseForReasonsToDisableScanning=_didPauseForReasonsToDisableScanning - In the implementation block
@property (nonatomic,retain) AXSwitchRecipe * currentRecipe;                                     //@synthesize currentRecipe=_currentRecipe - In the implementation block
@property (assign,nonatomic) long long itemMenuState;                                            //@synthesize itemMenuState=_itemMenuState - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)updateElementCacheScheme;
+(id)sharedManager;
-(void)pauseScanning;
-(void)unloadScanner;
-(void)loadScanner;
-(void)beginScanningWithFocusContext:(id)arg1 ;
-(SCATPointPicker *)pointPicker;
-(void)pointPickerDidFinishSweeping:(id)arg1 ;
-(SCATElementManager *)activeElementManager;
-(void)driver:(id)arg1 willFocusOnContext:(id)arg2 ;
-(void)driver:(id)arg1 didFocusOnContext:(id)arg2 ;
-(id)activeElementManagerForDriver:(id)arg1 ;
-(SCATActionHandler *)selectActionHandler;
-(SCATDriver *)activeScannerDriver;
-(BOOL)activateElement:(id)arg1 ;
-(void)endScanning;
-(void)driverDidPause:(id)arg1 ;
-(void)driverDidBecomeInactive:(id)arg1 ;
-(void)driverDidBecomeActive:(id)arg1 ;
-(unsigned long long)immediateSelectActionCount;
-(void)continueScanningWithFocusContext:(id)arg1 ;
-(void)resumeScanning;
-(BOOL)actionHandler:(id)arg1 shouldActImmediatelyOnActionCount:(unsigned long long)arg2 ;
-(void)actionHandlerDidFireAction:(id)arg1 ;
-(id)focusContextForActionHandler:(id)arg1 ;
-(void)actionHandlerDidCancelPendingAction:(id)arg1 ;
-(void)accessibilityManager:(id)arg1 didReceiveEvent:(long long)arg2 ;
-(void)accessibilityManager:(id)arg1 didScheduleFetchEvent:(long long)arg2 ;
-(void)accessibilityManager:(id)arg1 willFetchElementsForEvent:(long long)arg2 ;
-(void)accessibilityManager:(id)arg1 didFetchElementsForEvent:(long long)arg2 foundNewElements:(BOOL)arg3 ;
-(void)accessibilityManagerShouldPauseScanning:(id)arg1 ;
-(void)accessibilityManagerShouldResumeScanning:(id)arg1 ;
-(BOOL)isSwitchWithSource:(id)arg1 ;
-(BOOL)candidateBarManager:(id)arg1 hasValidTypingCandidates:(id)arg2 ;
-(void)useFocusContextOnResume:(id)arg1 ;
-(id)_typingCandidates;
-(void)alternateKeysManager:(id)arg1 didSelectAlternateKey:(id)arg2 ;
-(void)menu:(id)arg1 activateRecipe:(id)arg2 ;
-(id)scatUIContext;
-(void)inputController:(id)arg1 didReceiveRecipeActionForMappingAtIndex:(unsigned long long)arg2 isLongPressAction:(BOOL)arg3 ;
-(void)inputController:(id)arg1 didReceiveAction:(long long)arg2 ;
-(id)userInterfaceClientForInputController:(id)arg1 ;
-(AXUIClient *)userInterfaceClient;
-(CGRect)menu:(id)arg1 rectToClearForFingersWithGestureSheet:(BOOL)arg2 ;
-(void)driver:(id)arg1 indicateDwellScanningWillAbort:(BOOL)arg2 ;
-(id)contentViewForGestureProvider:(id)arg1 ;
-(void)addReasonToDisableScanning:(id)arg1 ;
-(void)removeReasonToDisableScanning:(id)arg1 ;
-(void)gestureProvider:(id)arg1 didShowFingers:(BOOL)arg2 ;
-(void)didChooseCreateCustomGestureFromGestureProvider:(id)arg1 ;
-(void)gestureProvider:(id)arg1 shouldResetScanningFromElement:(id)arg2 ;
-(void)shouldStartScanningGestureProvider:(id)arg1 ;
-(void)shouldEndScanningGestureProvider:(id)arg1 ;
-(void)menuWillAppear:(id)arg1 ;
-(void)menuDidAppear:(id)arg1 ;
-(void)menuDidDisappear:(id)arg1 ;
-(void)menuWillBeginTransition:(id)arg1 ;
-(void)menuDidFinishTransition:(id)arg1 ;
-(void)menuDidUpdateTipObject:(id)arg1 ;
-(void)pointPicker:(id)arg1 didPickPoint:(CGPoint)arg2 ;
-(void)pointPicker:(id)arg1 didSweepIntoFocusContext:(id)arg2 isRefiningPoint:(BOOL)arg3 ;
-(void)pointPicker:(id)arg1 didSweepOutOfFocusContext:(id)arg2 isRefiningPoint:(BOOL)arg3 ;
-(SCATCursorManager *)cursorManager;
-(void)setCursorManager:(SCATCursorManager *)arg1 ;
-(id)scatFrontCursorUIContext;
-(id)scatBackCursorUIContext;
-(BOOL)isUIContextHidden;
-(void)hidUIContext:(BOOL)arg1 ;
-(void)showUIContext:(BOOL)arg1 ;
-(void)presentPostScanningMenuForElementNavigationController:(id)arg1 ;
-(id)axManager;
-(SCATFocusContext *)currentFocusContext;
-(void)pauseScanningWithScreenLockDisabled:(BOOL)arg1 ;
-(void)setPointPicker:(SCATPointPicker *)arg1 ;
-(id)exitActionElementForFingersInMenu:(id)arg1 ;
-(long long)scanningMode;
-(void)actionHandlerForUI:(id)arg1 willPerformDelayedActionOnContext:(id)arg2 withCount:(unsigned long long)arg3 ;
-(void)actionHandlerForUIDidCancelPendingAction:(id)arg1 ;
-(void)actionHandlerForUIWillFireAction:(id)arg1 ;
-(BOOL)shouldShowAppWideScrollActionsInMenu:(id)arg1 ;
-(id)menu:(id)arg1 tapContextItemForSheet:(id)arg2 ;
-(id)menu:(id)arg1 tapAndHoldContextItemForSheet:(id)arg2 ;
-(BOOL)shouldAddItemSpecificMenuOptionsToMenu:(id)arg1 ;
-(long long)itemMenuStateForMenu:(id)arg1 ;
-(BOOL)isUsingPointMode;
-(void)menu:(id)arg1 showTypingCandidates:(id)arg2 ;
-(id)gesturesSheetForMenu:(id)arg1 ;
-(void)menu:(id)arg1 showAlternateKeysForKey:(id)arg2 ;
-(void)menu:(id)arg1 setItemMenuState:(long long)arg2 ;
-(void)menu:(id)arg1 showScrollViewPickerForScrollViews:(id)arg2 elementsToScroll:(id)arg3 scrollAction:(int)arg4 ;
-(HNDScannerAutoscroller *)autoscroller;
-(BOOL)areSoundEffectsEnabled;
-(BOOL)isSpeechEnabled;
-(BOOL)cursorManagerShouldHideMenuCursor:(id)arg1 ;
-(void)didPressScreenChangingButtonInMenu:(id)arg1 ;
-(BOOL)shouldBypassShowingMenu;
-(void)_performAccessibilityValidations;
-(void)_setupUserInterfaceClient;
-(void)setOutputManager:(AXOutputManager *)arg1 ;
-(void)setBeginScanningTimer:(AXDispatchTimer *)arg1 ;
-(void)setSelectActionHandler:(SCATActionHandler *)arg1 ;
-(void)setAutoscroller:(HNDScannerAutoscroller *)arg1 ;
-(void)setGestureProvider:(SCATGestureProvider *)arg1 ;
-(void)setElementNavController:(HNDElementNavigationController *)arg1 ;
-(void)setAlternateKeysManager:(SCATAlternateKeysManager *)arg1 ;
-(void)setCandidateBarManager:(SCATCandidateBarManager *)arg1 ;
-(id)_elementManagerForScannerState;
-(void)setActiveElementManager:(SCATElementManager *)arg1 ;
-(void)setAutoScanningDriver:(SCATAutomaticDriver *)arg1 ;
-(void)setManualScanningDriver:(SCATManualDriver *)arg1 ;
-(void)setDwellScanningDriver:(SCATDwellDriver *)arg1 ;
-(id)_driverForScannerState;
-(void)setActiveScannerDriver:(SCATDriver *)arg1 ;
-(void)_updateScanningStyle;
-(HNDElementNavigationController *)elementNavController;
-(void)_updateActiveElementManager;
-(void)_updateAudioSessionState;
-(void)_applyLaunchRecipeUUID;
-(SCATGestureProvider *)gestureProvider;
-(SCATAlternateKeysManager *)alternateKeysManager;
-(SCATCandidateBarManager *)candidateBarManager;
-(void)setScrollViewPickerManager:(SCATScrollViewPickerManager *)arg1 ;
-(void)setFocusContextForResume:(SCATFocusContext *)arg1 ;
-(void)setReasonsToDisableScanning:(NSMutableSet *)arg1 ;
-(void)_setCurrentRecipe:(id)arg1 shouldShowAlert:(BOOL)arg2 ;
-(void)_cleanupUserInterfaceClient;
-(BOOL)isAutoscanEnabled;
-(SCATAutomaticDriver *)autoScanningDriver;
-(SCATManualDriver *)manualScanningDriver;
-(SCATDwellDriver *)dwellScanningDriver;
-(SCATScrollViewPickerManager *)scrollViewPickerManager;
-(id)_primaryElementManagerForScannerState;
-(AXOutputManager *)outputManager;
-(void)_deactivateAudioSession;
-(AXSwitchRecipe *)currentRecipe;
-(long long)itemMenuState;
-(void)_beginOrContinueScanningWithFocusContext:(id)arg1 shouldBegin:(BOOL)arg2 ;
-(BOOL)_shouldIgnoreAllScannerControlMessages;
-(AXDispatchTimer *)beginScanningTimer;
-(BOOL)didSetFocusContextForResume;
-(SCATFocusContext *)focusContextForResume;
-(void)setForceDisableScreenLock:(BOOL)arg1 ;
-(NSMutableSet *)reasonsToDisableScanning;
-(void)setDidPauseForReasonsToDisableScanning:(BOOL)arg1 ;
-(BOOL)didPauseForReasonsToDisableScanning;
-(void)setDidSetFocusContextForResume:(BOOL)arg1 ;
-(void)_exitRecipeOnTimeout;
-(void)setCurrentRecipe:(AXSwitchRecipe *)arg1 ;
-(void)_showSimpleAlertWithText:(id)arg1 ;
-(void)_resetRecipeTimeoutIfApplicable;
-(void)setUserInterfaceClient:(AXUIClient *)arg1 ;
-(void)_driver:(id)arg1 outputAudioForContext:(id)arg2 ;
-(BOOL)_isScannerControlledByDriver:(id)arg1 ;
-(id<SCATElement>)currentElement;
-(void)_updateMenuAfterElementFetch;
-(void)_handleAppSwitcherAction;
-(void)_handleHomeAction;
-(void)_handleNotificationCenterAction;
-(void)_handleSiriAction;
-(void)_handleVolumeDownAction;
-(void)_handleForceTouchAction;
-(void)_handleVolumeUpAction;
-(BOOL)_isPostScanningMenu:(id)arg1 ;
-(void)setItemMenuState:(long long)arg1 ;
-(id)_focusContextAtPoint:(CGPoint)arg1 ;
-(BOOL)forceDisableScreenLock;
-(void)dealloc;
-(id)init;
-(NSString *)description;
-(BOOL)isActive;
-(SCATInputController *)inputController;
-(void)setInputController:(SCATInputController *)arg1 ;
-(BOOL)isLoaded;
-(SCATMenu *)menu;
-(void)setMenu:(SCATMenu *)arg1 ;
-(BOOL)isSystemSleeping;
-(BOOL)isLandscape;
-(BOOL)isGroupingEnabled;
-(BOOL)isInactive;
-(BOOL)isPaused;
@end

