/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, AXAccessQueueTimer;

@interface SCATInputSource : NSObject {

	BOOL _running;
	NSDictionary* _actions;
	/*^block*/id _fallbackActionBlock;
	AXAccessQueueTimer* _longPressTimer;
	long long _longPressActionIdentifier;
	double _buttonDownStartTime;

}

@property (nonatomic,retain) NSDictionary * actions;                           //@synthesize actions=_actions - In the implementation block
@property (assign,getter=isRunning,nonatomic) BOOL running;                    //@synthesize running=_running - In the implementation block
@property (nonatomic,copy) id fallbackActionBlock;                             //@synthesize fallbackActionBlock=_fallbackActionBlock - In the implementation block
@property (nonatomic,retain) AXAccessQueueTimer * longPressTimer;              //@synthesize longPressTimer=_longPressTimer - In the implementation block
@property (assign,nonatomic) long long longPressActionIdentifier;              //@synthesize longPressActionIdentifier=_longPressActionIdentifier - In the implementation block
@property (nonatomic,readonly) double totalLongPressDuration; 
@property (nonatomic,readonly) double longPressDuration; 
@property (nonatomic,readonly) double inputHoldDuration; 
@property (nonatomic,readonly) BOOL inputHoldEnabled; 
@property (nonatomic,readonly) BOOL longPressEnabled; 
@property (assign,nonatomic) double buttonDownStartTime;                       //@synthesize buttonDownStartTime=_buttonDownStartTime - In the implementation block
-(id)actionsForSwitches:(id)arg1 withRecipe:(id)arg2 ;
-(void)_didReceiveActionWithIdentifier:(long long)arg1 start:(BOOL)arg2 ignoreInputHold:(BOOL)arg3 ;
-(void)_handleAction:(long long)arg1 longPressAction:(long long)arg2 start:(BOOL)arg3 ;
-(void)setLongPressActionIdentifier:(long long)arg1 ;
-(void)setButtonDownStartTime:(double)arg1 ;
-(void)setLongPressTimer:(AXAccessQueueTimer *)arg1 ;
-(AXAccessQueueTimer *)longPressTimer;
-(id)fallbackActionBlock;
-(void)setFallbackActionBlock:(id)arg1 ;
-(BOOL)inputHoldEnabled;
-(double)inputHoldDuration;
-(double)longPressDuration;
-(BOOL)longPressEnabled;
-(double)totalLongPressDuration;
-(double)buttonDownStartTime;
-(long long)longPressActionIdentifier;
-(void)setActions:(NSDictionary *)arg1 ;
-(void)dealloc;
-(id)init;
-(NSDictionary *)actions;
-(BOOL)isRunning;
-(void)clearActions;
-(void)setRunning:(BOOL)arg1 ;
-(void)startRunning;
-(void)stopRunning;
@end

