/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCATModernMenuScrollSheetFallbackScrollAncestorDelegate <NSObject>
@required
-(void)scrollSheet:(id)arg1 performFallbackScrollAncestorAction:(int)arg2;
-(BOOL)scrollSheet:(id)arg1 shouldIncludeFallbackScrollAncestorActionsInVerticalDirection:(BOOL)arg2;
-(id)fallbackAncestorForScrollToTopInScrollSheet:(id)arg1;
-(id)fallbackAncestorForAutoscrollInScrollSheet:(id)arg1;

@end

