/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuSheet.h>

@class NSString, SCATModernMenuItem;

@interface SCATModernMenuDeviceSheet : SCATModernMenuSheet {

	NSString* _springBoardActionHandlerIdentifier;
	SCATModernMenuItem* _muteItem;

}

@property (nonatomic,copy) NSString * springBoardActionHandlerIdentifier;              //@synthesize springBoardActionHandlerIdentifier=_springBoardActionHandlerIdentifier - In the implementation block
@property (nonatomic,retain) SCATModernMenuItem * muteItem;                            //@synthesize muteItem=_muteItem - In the implementation block
-(BOOL)shouldUpdateMenuItem:(id)arg1 ;
-(void)menuItemWasActivated:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(id)initWithMenu:(id)arg1 ;
-(SCATModernMenuItem *)muteItem;
-(void)setSpringBoardActionHandlerIdentifier:(NSString *)arg1 ;
-(NSString *)springBoardActionHandlerIdentifier;
-(void)setMuteItem:(SCATModernMenuItem *)arg1 ;
-(void)_handleSpeakThis;
-(void)dealloc;
@end

