/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuSheet.h>

@protocol SCATModernMenuScrollSheetFallbackScrollAncestorDelegate;
@class AXElement;

@interface SCATModernMenuScrollSheet : SCATModernMenuSheet {

	AXElement* _scrollableElement;
	id<SCATModernMenuScrollSheetFallbackScrollAncestorDelegate> _fallbackScrollAncestorDelegate;

}

@property (nonatomic,readonly) id<SCATModernMenuScrollSheetFallbackScrollAncestorDelegate> fallbackScrollAncestorDelegate;              //@synthesize fallbackScrollAncestorDelegate=_fallbackScrollAncestorDelegate - In the implementation block
@property (nonatomic,retain) AXElement * scrollableElement;                                                                             //@synthesize scrollableElement=_scrollableElement - In the implementation block
+(BOOL)isValidForElement:(id)arg1 ;
-(void)menuItemWasActivated:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(long long)preferredTipObject;
-(AXElement *)scrollableElement;
-(id)initWithMenu:(id)arg1 scrollableElement:(id)arg2 fallbackScrollAncestorDelegate:(id)arg3 ;
-(void)_performScrollAction:(int)arg1 ;
-(void)setScrollableElement:(AXElement *)arg1 ;
-(id<SCATModernMenuScrollSheetFallbackScrollAncestorDelegate>)fallbackScrollAncestorDelegate;
-(void)dealloc;
-(void)reload;
@end

