/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATElementManager.h>

@protocol SCATPointPickerDelegate;
@class NSValue, SCATPointPickerViewController;

@interface SCATPointPicker : SCATElementManager {

	BOOL _shouldKeepScannerAwake;
	id<SCATPointPickerDelegate> _delegate;
	NSValue* _realPickedPoint;
	unsigned long long _refinementCount;
	long long _pickerType;

}

@property (assign,nonatomic) id<SCATPointPickerDelegate> delegate;                                //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) SCATPointPickerViewController * pickerViewController; 
@property (nonatomic,readonly) long long pickerType;                                              //@synthesize pickerType=_pickerType - In the implementation block
@property (nonatomic,readonly) BOOL allowsSelectionRefinement; 
@property (nonatomic,readonly) BOOL hasPickedPoint; 
@property (nonatomic,readonly) CGPoint pickedPoint; 
@property (nonatomic,readonly) CGPoint pickedPointInDeviceCoordinates; 
@property (assign,nonatomic) BOOL shouldKeepScannerAwake;                                         //@synthesize shouldKeepScannerAwake=_shouldKeepScannerAwake - In the implementation block
@property (nonatomic,retain) NSValue * realPickedPoint;                                           //@synthesize realPickedPoint=_realPickedPoint - In the implementation block
@property (assign,nonatomic) unsigned long long refinementCount;                                  //@synthesize refinementCount=_refinementCount - In the implementation block
+(id)mostSuitablePointPickerWithMenu:(id)arg1 ;
+(id)pointPickerWithMode:(long long)arg1 menu:(id)arg2 ;
-(unsigned long long)refinementCount;
-(CGPoint)pickedPointInDeviceCoordinates;
-(void)_savePoint:(CGPoint)arg1 andNotifyDelegate:(BOOL)arg2 ;
-(BOOL)isRefiningPoint;
-(BOOL)shouldKeepScannerAwake;
-(id)initWithMenu:(id)arg1 ;
-(void)didFetchElements:(id)arg1 foundNewElements:(BOOL)arg2 currentFocusContext:(id)arg3 didChangeActiveElementManager:(BOOL)arg4 ;
-(void)setShouldKeepScannerAwake:(BOOL)arg1 ;
-(CGPoint)pickedPoint;
-(void)scannerManager:(id)arg1 didActivateElement:(id)arg2 ;
-(BOOL)hasPickedPoint;
-(void)resetRefinedSelectedPoint;
-(BOOL)allowsSelectionRefinement;
-(void)refineSelectedPoint;
-(long long)pickerType;
-(void)setRealPickedPoint:(NSValue *)arg1 ;
-(NSValue *)realPickedPoint;
-(void)setRefinementCount:(unsigned long long)arg1 ;
-(void)setDelegate:(id<SCATPointPickerDelegate>)arg1 ;
-(void)dealloc;
-(id)description;
-(id<SCATPointPickerDelegate>)delegate;
-(id)identifier;
-(SCATPointPickerViewController *)pickerViewController;
@end

