/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATInputSource.h>
#import <assistivetouchd/AXEventHandler.h>

@protocol SCATHardwareInputSourceDelegate;
@class AXAccessQueue, NSString;

@interface SCATHardwareInputSource : SCATInputSource <AXEventHandler> {

	char* _hidReportBuffer;
	BOOL _available;
	id<SCATHardwareInputSourceDelegate> _delegate;
	AXAccessQueue* _queue;
	IOHIDManagerRef _hidManager;
	unsigned long long _availabilityDetail;

}

@property (assign,getter=isAvailable,nonatomic) BOOL available;                         //@synthesize available=_available - In the implementation block
@property (assign,nonatomic) id<SCATHardwareInputSourceDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) AXAccessQueue * queue;                                     //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic) IOHIDManagerRef hidManager;                                //@synthesize hidManager=_hidManager - In the implementation block
@property (assign,nonatomic) unsigned long long availabilityDetail;                     //@synthesize availabilityDetail=_availabilityDetail - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)handledEvent:(id)arg1 ;
-(id)actionsForSwitches:(id)arg1 withRecipe:(id)arg2 ;
-(void)_didReceiveActionWithIdentifier:(long long)arg1 start:(BOOL)arg2 ignoreInputHold:(BOOL)arg3 ;
-(BOOL)isMFIInputSource;
-(void)_startHandlingEvents;
-(void)_stopHandlingEvents;
-(BOOL)isKeyboardInputSource;
-(long long)_switchKeyForSwitch:(id)arg1 ;
-(NSString*)_switchSource;
-(unsigned long long)availabilityDetail;
-(void)setAvailabilityDetail:(unsigned long long)arg1 ;
-(id)_matchingCriteria;
-(void)_didUpdateAvailability:(BOOL)arg1 withDetail:(unsigned long long)arg2 ;
-(void)_startDetectingDevices;
-(void)_stopDetectingDevices;
-(void)setDelegate:(id<SCATHardwareInputSourceDelegate>)arg1 ;
-(void)dealloc;
-(id<SCATHardwareInputSourceDelegate>)delegate;
-(unsigned long long)priority;
-(AXAccessQueue *)queue;
-(void)setAvailable:(BOOL)arg1 ;
-(void)setDelegate:(id)arg1 queue:(id)arg2 ;
-(BOOL)isAvailable;
-(void)setQueue:(AXAccessQueue *)arg1 ;
-(void)startRunning;
-(void)stopRunning;
-(IOHIDManagerRef)hidManager;
-(void)setHidManager:(IOHIDManagerRef)arg1 ;
@end

