/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <assistivetouchd/SCATCursorLayer.h>

@interface SCATForegroundCursorLayer : SCATCursorLayer
-(double)_boundsInsetForTheme:(int)arg1 level:(int)arg2 highVisibility:(BOOL)arg3 options:(int)arg4 ;
-(double)_borderWidthForTheme:(int)arg1 level:(int)arg2 highVisibility:(BOOL)arg3 options:(int)arg4 ;
-(id)_borderPatternForTheme:(int)arg1 level:(int)arg2 highVisibility:(BOOL)arg3 options:(int)arg4 ;
-(void)updatePath:(id)arg1 frame:(CGRect)arg2 isSimpleRect:(BOOL)arg3 animated:(BOOL)arg4 options:(int)arg5 ;
@end

