/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuGesturesSheetBase.h>

@protocol SCATMenuGeneralGestureItemsViewDelegate;
@interface SCATModernMenuGesturesSheet : SCATModernMenuGesturesSheetBase {

	id<SCATMenuGeneralGestureItemsViewDelegate> _delegate;

}

@property (assign,nonatomic) id<SCATMenuGeneralGestureItemsViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(BOOL)shouldUpdateMenuItem:(id)arg1 ;
-(void)menuItemWasActivated:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(id)_fingerItemStringForNumberOfFingers:(unsigned long long)arg1 ;
-(id)_imageNameForNumberOfFingers:(unsigned long long)arg1 ;
-(void)setDelegate:(id<SCATMenuGeneralGestureItemsViewDelegate>)arg1 ;
-(id<SCATMenuGeneralGestureItemsViewDelegate>)delegate;
@end

