/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UILabel, _UIBackdropView, NSString;

@interface SCATPromptView : UIView {

	UILabel* _promptLabel;
	_UIBackdropView* _backdropView;

}

@property (nonatomic,copy) NSString * prompt; 
-(void)_updatePromptBackdropViewMask;
-(void)layoutSubviews;
-(NSString *)prompt;
-(void)setPrompt:(NSString *)arg1 ;
@end

