/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuGesturesSheetBase.h>

@protocol SCATMenuFlickItemsViewDelegate;
@interface SCATModernMenuGestureFlickSheet : SCATModernMenuGesturesSheetBase {

	id<SCATMenuFlickItemsViewDelegate> _delegate;

}

@property (assign,nonatomic) id<SCATMenuFlickItemsViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)menuItemWasActivated:(id)arg1 ;
-(id)makeMenuItemsIfNeeded;
-(void)setDelegate:(id<SCATMenuFlickItemsViewDelegate>)arg1 ;
-(id<SCATMenuFlickItemsViewDelegate>)delegate;
@end

