/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/assistivetouchd-Structs.h>
#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UIImage, SCATModernMenuItem;

@interface SCATModernMenuItemCell : UICollectionViewCell {

	UIImageView* _backgroundBorderImageView;
	UIImageView* _pressedBackgroundBorderImageView;
	UIImage* _pressedBackgroundImage;
	UIImage* _defaultBackgroundImage;
	UIImage* _dimmedBackgroundImage;
	UIImageView* _iconImageView;
	UIImage* _dimmedIconImage;
	UIImage* _highVisBackgroundAndIconImage;
	SCATModernMenuItem* _menuItem;
	UIImage* _iconImage;
	double _iconImageAngle;

}

@property (nonatomic,retain) UIImage * iconImage;                                         //@synthesize iconImage=_iconImage - In the implementation block
@property (assign,nonatomic) SCATModernMenuItem * menuItem;                               //@synthesize menuItem=_menuItem - In the implementation block
@property (nonatomic,retain) UIImageView * pressedBackgroundBorderImageView;              //@synthesize pressedBackgroundBorderImageView=_pressedBackgroundBorderImageView - In the implementation block
@property (assign,nonatomic) double iconImageAngle;                                       //@synthesize iconImageAngle=_iconImageAngle - In the implementation block
@property (nonatomic,retain) UIImage * defaultBackgroundImage;                            //@synthesize defaultBackgroundImage=_defaultBackgroundImage - In the implementation block
@property (nonatomic,retain) UIImage * pressedBackgroundImage;                            //@synthesize pressedBackgroundImage=_pressedBackgroundImage - In the implementation block
@property (nonatomic,retain) UIImage * dimmedBackgroundImage;                             //@synthesize dimmedBackgroundImage=_dimmedBackgroundImage - In the implementation block
@property (nonatomic,retain) UIImageView * backgroundBorderImageView;                     //@synthesize backgroundBorderImageView=_backgroundBorderImageView - In the implementation block
@property (nonatomic,retain) UIImage * dimmedIconImage;                                   //@synthesize dimmedIconImage=_dimmedIconImage - In the implementation block
@property (nonatomic,retain) UIImage * highVisBackgroundAndIconImage;                     //@synthesize highVisBackgroundAndIconImage=_highVisBackgroundAndIconImage - In the implementation block
@property (nonatomic,retain) UIImageView * iconImageView;                                 //@synthesize iconImageView=_iconImageView - In the implementation block
-(BOOL)scatIndicatesOwnFocus;
-(BOOL)scatSupportsAction:(int)arg1 ;
-(id)scatSpeakableDescription;
-(BOOL)scatPerformAction:(int)arg1 ;
-(CGRect)scatFrame;
-(void)setMenuItem:(SCATModernMenuItem *)arg1 ;
-(void)didUpdateScatMenuItemStyle;
-(void)setIconImageAngle:(double)arg1 ;
-(void)setBackgroundBorderImageView:(UIImageView *)arg1 ;
-(void)setPressedBackgroundBorderImageView:(UIImageView *)arg1 ;
-(UIImageView *)pressedBackgroundBorderImageView;
-(void)setHighVisBackgroundAndIconImage:(UIImage *)arg1 ;
-(void)setPressedBackgroundImage:(UIImage *)arg1 ;
-(void)setDefaultBackgroundImage:(UIImage *)arg1 ;
-(void)setDimmedBackgroundImage:(UIImage *)arg1 ;
-(UIImage *)highVisBackgroundAndIconImage;
-(double)iconImageAngle;
-(UIImageView *)backgroundBorderImageView;
-(UIImage *)dimmedBackgroundImage;
-(UIImage *)defaultBackgroundImage;
-(void)_setBorderDimmed:(BOOL)arg1 focused:(BOOL)arg2 hidden:(BOOL)arg3 ;
-(void)_setIconDimmed:(BOOL)arg1 asDimAsBorder:(BOOL)arg2 focused:(BOOL)arg3 ;
-(BOOL)scatShouldActivateDirectly;
-(UIImage *)pressedBackgroundImage;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)description;
-(id)accessibilityLabel;
-(void)prepareForReuse;
-(UIImage *)iconImage;
-(SCATModernMenuItem *)menuItem;
-(void)setIconImage:(UIImage *)arg1 ;
-(UIImageView *)iconImageView;
-(void)setIconImageView:(UIImageView *)arg1 ;
-(void)setDimmedIconImage:(UIImage *)arg1 ;
-(UIImage *)dimmedIconImage;
@end

