/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATModernMenuItem.h>

@class NSString;

@interface SCATModernMenuGestureFreehandItem : SCATModernMenuItem {

	BOOL _shouldRotate;
	BOOL _disabled;
	BOOL _focused;
	NSString* _imagePrefixForTouchDependentGlyph;
	unsigned long long _preferredNumberOfTitleLines;

}

@property (nonatomic,retain) NSString * imagePrefixForTouchDependentGlyph;                //@synthesize imagePrefixForTouchDependentGlyph=_imagePrefixForTouchDependentGlyph - In the implementation block
@property (assign,nonatomic) BOOL shouldRotate;                                           //@synthesize shouldRotate=_shouldRotate - In the implementation block
@property (assign,getter=isDisabled,nonatomic) BOOL disabled;                             //@synthesize disabled=_disabled - In the implementation block
@property (assign,getter=isFocused,nonatomic) BOOL focused;                               //@synthesize focused=_focused - In the implementation block
@property (assign,nonatomic) unsigned long long preferredNumberOfTitleLines;              //@synthesize preferredNumberOfTitleLines=_preferredNumberOfTitleLines - In the implementation block
+(id)itemWithIdentifier:(id)arg1 delegate:(id)arg2 title:(id)arg3 imagePrefixForTouchDependentGlyph:(id)arg4 shouldRotate:(BOOL)arg5 activateBehavior:(unsigned long long)arg6 ;
+(id)itemWithIdentifier:(id)arg1 delegate:(id)arg2 title:(id)arg3 activateBehavior:(unsigned long long)arg4 ;
+(id)itemWithIdentifier:(id)arg1 delegate:(id)arg2 title:(id)arg3 imagePrefixForTouchDependentGlyph:(id)arg4 activateBehavior:(unsigned long long)arg5 ;
-(void)setImagePrefixForTouchDependentGlyph:(NSString *)arg1 ;
-(void)setPreferredNumberOfTitleLines:(unsigned long long)arg1 ;
-(unsigned long long)preferredNumberOfTitleLines;
-(NSString *)imagePrefixForTouchDependentGlyph;
-(BOOL)shouldRotate;
-(BOOL)handleActivateWithElement:(id)arg1 ;
-(void)setShouldRotate:(BOOL)arg1 ;
-(void)dealloc;
-(BOOL)isFocused;
-(void)setDisabled:(BOOL)arg1 ;
-(void)setFocused:(BOOL)arg1 ;
-(BOOL)isDisabled;
@end

