/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <assistivetouchd/SCATElementProvider.h>

@class NSMutableOrderedSet, NSString;

@interface SCATAggregateElementProvider : NSObject <SCATElementProvider> {

	NSMutableOrderedSet* _providers;

}

@property (nonatomic,retain) NSMutableOrderedSet * providers;              //@synthesize providers=_providers - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) BOOL providesElements; 
-(id)lastElementWithOptions:(int*)arg1 ;
-(id)firstElementWithOptions:(int*)arg1 ;
-(BOOL)providesElements;
-(id)elementAfter:(id)arg1 didWrap:(BOOL*)arg2 options:(int*)arg3 ;
-(id)elementBefore:(id)arg1 didWrap:(BOOL*)arg2 options:(int*)arg3 ;
-(void)addProvider:(id)arg1 ;
-(id)addProviderWithElements:(id)arg1 passingTest:(/*^block*/id)arg2 ;
-(BOOL)containsElement:(id)arg1 ;
-(void)willBeginProvidingElements;
-(void)didFinishProvidingElements;
-(unsigned long long)_indexOfProviderContainingElement:(id)arg1 ;
-(unsigned long long)_indexOfProviderBeforeProviderWithIndex:(unsigned long long)arg1 didWrap:(BOOL*)arg2 ;
-(unsigned long long)_indexOfProviderAfterProviderWithIndex:(unsigned long long)arg1 didWrap:(BOOL*)arg2 ;
-(void)removeAllProviders;
-(void)dealloc;
-(id)init;
-(NSString *)description;
-(void)removeProvider:(id)arg1 ;
-(NSMutableOrderedSet *)providers;
-(void)setProviders:(NSMutableOrderedSet *)arg1 ;
@end

