/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCATActionHandlerDelegate, SCATActionHandlerUIDelegate;
@class AXAccessQueueTimer;

@interface SCATActionHandler : NSObject {

	long long _action;
	id<SCATActionHandlerDelegate> _delegate;
	id<SCATActionHandlerUIDelegate> _uiDelegate;
	AXAccessQueueTimer* _actionTimeoutTimer;
	unsigned long long _actionCount;
	double _timeoutDuration;

}

@property (assign,nonatomic) id<SCATActionHandlerDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) id<SCATActionHandlerUIDelegate> uiDelegate;              //@synthesize uiDelegate=_uiDelegate - In the implementation block
@property (assign,nonatomic) double timeoutDuration;                                  //@synthesize timeoutDuration=_timeoutDuration - In the implementation block
@property (assign,nonatomic) unsigned long long actionCount;                          //@synthesize actionCount=_actionCount - In the implementation block
@property (nonatomic,readonly) BOOL shouldShowMenuOnFirstSelectAction; 
@property (nonatomic,retain) AXAccessQueueTimer * actionTimeoutTimer;                 //@synthesize actionTimeoutTimer=_actionTimeoutTimer - In the implementation block
@property (assign,nonatomic) long long action;                                        //@synthesize action=_action - In the implementation block
-(void)cancelPendingAction;
-(void)notifyDidReceiveAction:(id)arg1 ;
-(unsigned long long)actionCount;
-(BOOL)shouldShowMenuOnFirstSelectAction;
-(void)setActionTimeoutTimer:(AXAccessQueueTimer *)arg1 ;
-(void)_resetWithActionSource:(id)arg1 ;
-(void)setActionCount:(unsigned long long)arg1 ;
-(BOOL)_shouldHandleSelectActionImmediately;
-(AXAccessQueueTimer *)actionTimeoutTimer;
-(void)_handleFireAction;
-(id)initWithAction:(long long)arg1 timeoutDuration:(double)arg2 ;
-(void)setDelegate:(id<SCATActionHandlerDelegate>)arg1 ;
-(void)dealloc;
-(id<SCATActionHandlerDelegate>)delegate;
-(long long)action;
-(void)setAction:(long long)arg1 ;
-(void)setUiDelegate:(id<SCATActionHandlerUIDelegate>)arg1 ;
-(id<SCATActionHandlerUIDelegate>)uiDelegate;
-(double)timeoutDuration;
-(void)setTimeoutDuration:(double)arg1 ;
@end

