/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:24 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCATGestureDrawingViewDelegate <NSObject>
@required
-(void)touchDownForDrawingViewController:(id)arg1;
-(void)touchUpForDrawingViewController:(id)arg1;
-(BOOL)drawingViewController:(id)arg1 moveFingersToPoints:(id)arg2;
-(void)exitDrawingViewController:(id)arg1;
-(void)drawingViewController:(id)arg1 shouldResetScanningFromElement:(id)arg2;

@end

