/*
* This header is generated by classdump-dyld 1.0
* on Monday, August 15, 2016 at 11:35:25 AM Eastern Daylight Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/CoreServices/AssistiveTouch.app/assistivetouchd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UICollectionViewDelegateSCATMenuLayout <UICollectionViewDelegate>
@required
-(id)menuSheetForCollectionView:(id)arg1;
-(CGSize*)sizeForItemTitleTextAtIndexPath:(id)arg1 withMaxSize:(CGSize)arg2;
-(id)titleTextForItemAtIndexPath:(id)arg1;

@end

